// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>loan_installments.status</c>, enforced by the database CHECK constraint
/// <c>chk_loan_installments_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_loan_installments_status
{
    public const string Table = "loan_installments";
    public const string Column = "status";
    public const string ConstraintName = "chk_loan_installments_status";
    public const bool NullAllowed = false;

    public const string Due = "Due";
    public const string Recovered = "Recovered";
    public const string Waived = "Waived";
    public const string Cancelled = "Cancelled";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Due,
        Recovered,
        Waived,
        Cancelled,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
