// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>payroll_inputs.status</c>, enforced by the database CHECK constraint
/// <c>chk_payroll_inputs_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_payroll_inputs_status
{
    public const string Table = "payroll_inputs";
    public const string Column = "status";
    public const string ConstraintName = "chk_payroll_inputs_status";
    public const bool NullAllowed = false;

    public const string Pending = "Pending";
    public const string Claimed = "Claimed";
    public const string Consumed = "Consumed";
    public const string Cancelled = "Cancelled";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Pending,
        Claimed,
        Consumed,
        Cancelled,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
