// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>timesheet_day_reconciliations.status</c>, enforced by the database CHECK constraint
/// <c>chk_tsdr_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_tsdr_status
{
    public const string Table = "timesheet_day_reconciliations";
    public const string Column = "status";
    public const string ConstraintName = "chk_tsdr_status";
    public const bool NullAllowed = false;

    public const string Open = "Open";
    public const string Explained = "Explained";
    public const string Accepted = "Accepted";
    public const string Rejected = "Rejected";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Open,
        Explained,
        Accepted,
        Rejected,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
