// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>employee_documents.status</c>, enforced by the database CHECK constraint
/// <c>chk_employee_documents_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_employee_documents_status
{
    public const string Table = "employee_documents";
    public const string Column = "status";
    public const string ConstraintName = "chk_employee_documents_status";
    public const bool NullAllowed = false;

    public const string Active = "Active";
    public const string Expired = "Expired";
    public const string Superseded = "Superseded";
    public const string Revoked = "Revoked";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Active,
        Expired,
        Superseded,
        Revoked,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
