// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>loans.status</c>, enforced by the database CHECK constraint
/// <c>chk_loans_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_loans_status
{
    public const string Table = "loans";
    public const string Column = "status";
    public const string ConstraintName = "chk_loans_status";
    public const bool NullAllowed = false;

    public const string PendingApproval = "PendingApproval";
    public const string Active = "Active";
    public const string Settled = "Settled";
    public const string Cancelled = "Cancelled";
    public const string Rejected = "Rejected";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        PendingApproval,
        Active,
        Settled,
        Cancelled,
        Rejected,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
