// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>payroll_slips.inclusion_status</c>, enforced by the database CHECK constraint
/// <c>chk_payroll_slips_inclusion</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_payroll_slips_inclusion
{
    public const string Table = "payroll_slips";
    public const string Column = "inclusion_status";
    public const string ConstraintName = "chk_payroll_slips_inclusion";
    public const bool NullAllowed = false;

    public const string Included = "Included";
    public const string ExcludedByFilter = "ExcludedByFilter";
    public const string ExcludedByHold = "ExcludedByHold";
    public const string ExcludedByBlock = "ExcludedByBlock";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Included,
        ExcludedByFilter,
        ExcludedByHold,
        ExcludedByBlock,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
