// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>approval_actions.action</c>, enforced by the database CHECK constraint
/// <c>chk_approval_actions_action</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_approval_actions_action
{
    public const string Table = "approval_actions";
    public const string Column = "action";
    public const string ConstraintName = "chk_approval_actions_action";
    public const bool NullAllowed = false;

    public const string Approve = "Approve";
    public const string Reject = "Reject";
    public const string Return = "Return";
    public const string Comment = "Comment";
    public const string Escalate = "Escalate";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Approve,
        Reject,
        Return,
        Comment,
        Escalate,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
