// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>notification_deliveries.status</c>, enforced by the database CHECK constraint
/// <c>chk_notification_deliveries_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_notification_deliveries_status
{
    public const string Table = "notification_deliveries";
    public const string Column = "status";
    public const string ConstraintName = "chk_notification_deliveries_status";
    public const bool NullAllowed = false;

    public const string Queued = "Queued";
    public const string Sent = "Sent";
    public const string Delivered = "Delivered";
    public const string Failed = "Failed";
    public const string Suppressed = "Suppressed";
    public const string DeadLettered = "DeadLettered";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Queued,
        Sent,
        Delivered,
        Failed,
        Suppressed,
        DeadLettered,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
