// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>employee_documents.doc_type</c>, enforced by the database CHECK constraint
/// <c>chk_employee_documents_type</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_employee_documents_type
{
    public const string Table = "employee_documents";
    public const string Column = "doc_type";
    public const string ConstraintName = "chk_employee_documents_type";
    public const bool NullAllowed = false;

    public const string Iqama = "Iqama";
    public const string Passport = "Passport";
    public const string Visa = "Visa";
    public const string WorkPermit = "WorkPermit";
    public const string Contract = "Contract";
    public const string Letter = "Letter";
    public const string Medical = "Medical";
    public const string Other = "Other";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Iqama,
        Passport,
        Visa,
        WorkPermit,
        Contract,
        Letter,
        Medical,
        Other,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
