// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>wps_lines.bank_status</c>, enforced by the database CHECK constraint
/// <c>chk_wps_lines_bank_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_wps_lines_bank_status
{
    public const string Table = "wps_lines";
    public const string Column = "bank_status";
    public const string ConstraintName = "chk_wps_lines_bank_status";
    public const bool NullAllowed = false;

    public const string Pending = "Pending";
    public const string Paid = "Paid";
    public const string Rejected = "Rejected";
    public const string Returned = "Returned";
    public const string OnHold = "OnHold";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Pending,
        Paid,
        Rejected,
        Returned,
        OnHold,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
