// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>approval_requests.status</c>, enforced by the database CHECK constraint
/// <c>chk_approval_requests_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_approval_requests_status
{
    public const string Table = "approval_requests";
    public const string Column = "status";
    public const string ConstraintName = "chk_approval_requests_status";
    public const bool NullAllowed = false;

    public const string Draft = "Draft";
    public const string Pending = "Pending";
    public const string Approved = "Approved";
    public const string Rejected = "Rejected";
    public const string Returned = "Returned";
    public const string Cancelled = "Cancelled";
    public const string Expired = "Expired";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Draft,
        Pending,
        Approved,
        Rejected,
        Returned,
        Cancelled,
        Expired,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
