// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>payroll_runs.run_type</c>, enforced by the database CHECK constraint
/// <c>chk_payroll_runs_type</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_payroll_runs_type
{
    public const string Table = "payroll_runs";
    public const string Column = "run_type";
    public const string ConstraintName = "chk_payroll_runs_type";
    public const bool NullAllowed = false;

    public const string Regular = "Regular";
    public const string OffCycle = "OffCycle";
    public const string FinalSettlement = "FinalSettlement";
    public const string Correction = "Correction";
    public const string Opening = "Opening";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Regular,
        OffCycle,
        FinalSettlement,
        Correction,
        Opening,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
