// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>eos_calculations.status</c>, enforced by the database CHECK constraint
/// <c>chk_eos_calculations_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_eos_calculations_status
{
    public const string Table = "eos_calculations";
    public const string Column = "status";
    public const string ConstraintName = "chk_eos_calculations_status";
    public const bool NullAllowed = false;

    public const string Estimate = "Estimate";
    public const string Final = "Final";
    public const string Superseded = "Superseded";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Estimate,
        Final,
        Superseded,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
