// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>auth_sessions.subject_kind</c>, enforced by the database CHECK constraint
/// <c>chk_auth_subject_kind_auth_sessions</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_auth_subject_kind_auth_sessions
{
    public const string Table = "auth_sessions";
    public const string Column = "subject_kind";
    public const string ConstraintName = "chk_auth_subject_kind_auth_sessions";
    public const bool NullAllowed = false;

    public const string Tenant = "Tenant";
    public const string Platform = "Platform";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Tenant,
        Platform,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
