// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>platform_users.status</c>, enforced by the database CHECK constraint
/// <c>chk_platform_users_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_platform_users_status
{
    public const string Table = "platform_users";
    public const string Column = "status";
    public const string ConstraintName = "chk_platform_users_status";
    public const bool NullAllowed = false;

    public const string Active = "Active";
    public const string Suspended = "Suspended";
    public const string Disabled = "Disabled";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Active,
        Suspended,
        Disabled,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
