// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>timesheets.status</c>, enforced by the database CHECK constraint
/// <c>chk_timesheets_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_timesheets_status
{
    public const string Table = "timesheets";
    public const string Column = "status";
    public const string ConstraintName = "chk_timesheets_status";
    public const bool NullAllowed = false;

    public const string Draft = "Draft";
    public const string Submitted = "Submitted";
    public const string Approved = "Approved";
    public const string Rejected = "Rejected";
    public const string Locked = "Locked";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Draft,
        Submitted,
        Approved,
        Rejected,
        Locked,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
