// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>employees.status</c>, enforced by the database CHECK constraint
/// <c>chk_employees_status</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_employees_status
{
    public const string Table = "employees";
    public const string Column = "status";
    public const string ConstraintName = "chk_employees_status";
    public const bool NullAllowed = false;

    public const string Draft = "Draft";
    public const string Invited = "Invited";
    public const string Active = "Active";
    public const string Suspended = "Suspended";
    public const string Offboarded = "Offboarded";
    public const string Archived = "Archived";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Draft,
        Invited,
        Active,
        Suspended,
        Offboarded,
        Archived,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
