// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>auth_tokens.purpose</c>, enforced by the database CHECK constraint
/// <c>chk_auth_tokens_purpose</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_auth_tokens_purpose
{
    public const string Table = "auth_tokens";
    public const string Column = "purpose";
    public const string ConstraintName = "chk_auth_tokens_purpose";
    public const bool NullAllowed = false;

    public const string PasswordReset = "PasswordReset";
    public const string MfaChallenge = "MfaChallenge";
    public const string Invitation = "Invitation";
    public const string EmailConfirm = "EmailConfirm";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        PasswordReset,
        MfaChallenge,
        Invitation,
        EmailConfirm,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
