// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>employees.privacy_status</c>, enforced by the database CHECK constraint
/// <c>chk_employees_privacy</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class chk_employees_privacy
{
    public const string Table = "employees";
    public const string Column = "privacy_status";
    public const string ConstraintName = "chk_employees_privacy";
    public const bool NullAllowed = false;

    public const string Normal = "Normal";
    public const string PendingErasure = "PendingErasure";
    public const string Anonymised = "Anonymised";
    public const string MergedDuplicate = "MergedDuplicate";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Normal,
        PendingErasure,
        Anonymised,
        MergedDuplicate,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
