// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>audit_logs.category</c>, enforced by the database CHECK constraint
/// <c>ck_audit_logs__category</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// The column is nullable: NULL is permitted and is not a member of ck_audit_logs__category.All.
/// </summary>
public static class ck_audit_logs__category
{
    public const string Table = "audit_logs";
    public const string Column = "category";
    public const string ConstraintName = "ck_audit_logs__category";
    public const bool NullAllowed = true;

    public const string Auth = "Auth";
    public const string Admin = "Admin";
    public const string Employee = "Employee";
    public const string Leave = "Leave";
    public const string Attendance = "Attendance";
    public const string Loan = "Loan";
    public const string Document = "Document";
    public const string ESS = "ESS";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Auth,
        Admin,
        Employee,
        Leave,
        Attendance,
        Loan,
        Document,
        ESS,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
