// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>audit_logs.record_kind</c>, enforced by the database CHECK constraint
/// <c>ck_audit_logs__record_kind</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_audit_logs__record_kind
{
    public const string Table = "audit_logs";
    public const string Column = "record_kind";
    public const string ConstraintName = "ck_audit_logs__record_kind";
    public const bool NullAllowed = false;

    public const string Event = "Event";
    public const string Checkpoint = "Checkpoint";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Event,
        Checkpoint,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
