// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>approval_workflows.request_type</c>, enforced by the database CHECK constraint
/// <c>ck_approval_workflows__request_type</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_approval_workflows__request_type
{
    public const string Table = "approval_workflows";
    public const string Column = "request_type";
    public const string ConstraintName = "ck_approval_workflows__request_type";
    public const bool NullAllowed = false;

    public const string Leave = "Leave";
    public const string LeaveCancel = "LeaveCancel";
    public const string Overtime = "Overtime";
    public const string Loan = "Loan";
    public const string Advance = "Advance";
    public const string PayrollRun = "PayrollRun";
    public const string FinalSettlement = "FinalSettlement";
    public const string ProfileChange = "ProfileChange";
    public const string Transfer = "Transfer";
    public const string SalaryChange = "SalaryChange";
    public const string LetterRequest = "LetterRequest";
    public const string AttendanceCorrection = "AttendanceCorrection";
    public const string Timesheet = "Timesheet";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Leave,
        LeaveCancel,
        Overtime,
        Loan,
        Advance,
        PayrollRun,
        FinalSettlement,
        ProfileChange,
        Transfer,
        SalaryChange,
        LetterRequest,
        AttendanceCorrection,
        Timesheet,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
