// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>attendance_punches.source</c>, enforced by the database CHECK constraint
/// <c>ck_attendance_punches__source</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_attendance_punches__source
{
    public const string Table = "attendance_punches";
    public const string Column = "source";
    public const string ConstraintName = "ck_attendance_punches__source";
    public const bool NullAllowed = false;

    public const string Device = "Device";
    public const string Mobile = "Mobile";
    public const string Import = "Import";
    public const string Correction = "Correction";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Device,
        Mobile,
        Import,
        Correction,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
