// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>document_templates.kind</c>, enforced by the database CHECK constraint
/// <c>ck_document_templates__kind</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_document_templates__kind
{
    public const string Table = "document_templates";
    public const string Column = "kind";
    public const string ConstraintName = "ck_document_templates__kind";
    public const bool NullAllowed = false;

    public const string Letter = "Letter";
    public const string Payslip = "Payslip";
    public const string Contract = "Contract";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Letter,
        Payslip,
        Contract,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
