// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>eos_calculations.separation_reason</c>, enforced by the database CHECK constraint
/// <c>ck_eos_calculations__separation_reason</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_eos_calculations__separation_reason
{
    public const string Table = "eos_calculations";
    public const string Column = "separation_reason";
    public const string ConstraintName = "ck_eos_calculations__separation_reason";
    public const bool NullAllowed = false;

    public const string Art84 = "Art84";
    public const string Art85 = "Art85";
    public const string Art87 = "Art87";
    public const string Art77 = "Art77";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Art84,
        Art85,
        Art87,
        Art77,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
