// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>files.purpose</c>, enforced by the database CHECK constraint
/// <c>ck_files__purpose</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_files__purpose
{
    public const string Table = "files";
    public const string Column = "purpose";
    public const string ConstraintName = "ck_files__purpose";
    public const bool NullAllowed = false;

    public const string EmployeeDocument = "EmployeeDocument";
    public const string Payslip = "Payslip";
    public const string WpsSif = "WpsSif";
    public const string GlExport = "GlExport";
    public const string BankConfirmation = "BankConfirmation";
    public const string Import = "Import";
    public const string LetterPdf = "LetterPdf";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        EmployeeDocument,
        Payslip,
        WpsSif,
        GlExport,
        BankConfirmation,
        Import,
        LetterPdf,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
