// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>final_settlements.separation_type</c>, enforced by the database CHECK constraint
/// <c>ck_final_settlements__separation_type</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_final_settlements__separation_type
{
    public const string Table = "final_settlements";
    public const string Column = "separation_type";
    public const string ConstraintName = "ck_final_settlements__separation_type";
    public const bool NullAllowed = false;

    public const string Resignation = "Resignation";
    public const string Termination = "Termination";
    public const string EndOfContract = "EndOfContract";
    public const string Retirement = "Retirement";
    public const string Death = "Death";
    public const string Abscond = "Abscond";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Resignation,
        Termination,
        EndOfContract,
        Retirement,
        Death,
        Abscond,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
