// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>final_settlement_lines.kind</c>, enforced by the database CHECK constraint
/// <c>ck_final_settlement_lines__kind</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_final_settlement_lines__kind
{
    public const string Table = "final_settlement_lines";
    public const string Column = "kind";
    public const string ConstraintName = "ck_final_settlement_lines__kind";
    public const bool NullAllowed = false;

    public const string EOS = "EOS";
    public const string LeaveEncashment = "LeaveEncashment";
    public const string UnpaidSalary = "UnpaidSalary";
    public const string NoticePay = "NoticePay";
    public const string Art77Compensation = "Art77Compensation";
    public const string LoanRecovery = "LoanRecovery";
    public const string OtherDeduction = "OtherDeduction";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        EOS,
        LeaveEncashment,
        UnpaidSalary,
        NoticePay,
        Art77Compensation,
        LoanRecovery,
        OtherDeduction,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
