// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>gl_journals.source_type</c>, enforced by the database CHECK constraint
/// <c>ck_gl_journals__source_type</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_gl_journals__source_type
{
    public const string Table = "gl_journals";
    public const string Column = "source_type";
    public const string ConstraintName = "ck_gl_journals__source_type";
    public const bool NullAllowed = false;

    public const string PayrollRun = "PayrollRun";
    public const string FinalSettlement = "FinalSettlement";
    public const string LoanDisbursement = "LoanDisbursement";
    public const string Reversal = "Reversal";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        PayrollRun,
        FinalSettlement,
        LoanDisbursement,
        Reversal,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
