// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>loan_installments.kind</c>, enforced by the database CHECK constraint
/// <c>ck_loan_installments__kind</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_loan_installments__kind
{
    public const string Table = "loan_installments";
    public const string Column = "kind";
    public const string ConstraintName = "ck_loan_installments__kind";
    public const bool NullAllowed = false;

    public const string Scheduled = "Scheduled";
    public const string EarlySettlement = "EarlySettlement";
    public const string FinalSettlement = "FinalSettlement";
    public const string Waiver = "Waiver";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Scheduled,
        EarlySettlement,
        FinalSettlement,
        Waiver,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
