// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>leave_ledger.entry_type</c>, enforced by the database CHECK constraint
/// <c>ck_leave_ledger__entry_type</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_leave_ledger__entry_type
{
    public const string Table = "leave_ledger";
    public const string Column = "entry_type";
    public const string ConstraintName = "ck_leave_ledger__entry_type";
    public const bool NullAllowed = false;

    public const string Opening = "Opening";
    public const string Accrual = "Accrual";
    public const string Debit = "Debit";
    public const string Reversal = "Reversal";
    public const string CarryForward = "CarryForward";
    public const string Expiry = "Expiry";
    public const string Encashment = "Encashment";
    public const string Adjustment = "Adjustment";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Opening,
        Accrual,
        Debit,
        Reversal,
        CarryForward,
        Expiry,
        Encashment,
        Adjustment,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
