// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>leave_requests.request_kind</c>, enforced by the database CHECK constraint
/// <c>ck_leave_requests__request_kind</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_leave_requests__request_kind
{
    public const string Table = "leave_requests";
    public const string Column = "request_kind";
    public const string ConstraintName = "ck_leave_requests__request_kind";
    public const bool NullAllowed = false;

    public const string Leave = "Leave";
    public const string Encashment = "Encashment";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Leave,
        Encashment,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
