// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>loans.kind</c>, enforced by the database CHECK constraint
/// <c>ck_loans__kind</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_loans__kind
{
    public const string Table = "loans";
    public const string Column = "kind";
    public const string ConstraintName = "ck_loans__kind";
    public const bool NullAllowed = false;

    public const string Loan = "Loan";
    public const string Advance = "Advance";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Loan,
        Advance,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
