// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>notification_deliveries.channel</c>, enforced by the database CHECK constraint
/// <c>ck_notification_deliveries__channel</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_notification_deliveries__channel
{
    public const string Table = "notification_deliveries";
    public const string Column = "channel";
    public const string ConstraintName = "ck_notification_deliveries__channel";
    public const bool NullAllowed = false;

    public const string Email = "Email";
    public const string Sms = "Sms";
    public const string Push = "Push";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Email,
        Sms,
        Push,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
