// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>nitaqat_grid.band</c>, enforced by the database CHECK constraint
/// <c>ck_nitaqat_grid__band</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_nitaqat_grid__band
{
    public const string Table = "nitaqat_grid";
    public const string Column = "band";
    public const string ConstraintName = "ck_nitaqat_grid__band";
    public const bool NullAllowed = false;

    public const string Platinum = "Platinum";
    public const string HighGreen = "HighGreen";
    public const string MidGreen = "MidGreen";
    public const string LowGreen = "LowGreen";
    public const string Red = "Red";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Platinum,
        HighGreen,
        MidGreen,
        LowGreen,
        Red,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
