// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>number_sequences.reset_period</c>, enforced by the database CHECK constraint
/// <c>ck_number_sequences__reset_period</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_number_sequences__reset_period
{
    public const string Table = "number_sequences";
    public const string Column = "reset_period";
    public const string ConstraintName = "ck_number_sequences__reset_period";
    public const bool NullAllowed = false;

    public const string None = "None";
    public const string Year = "Year";
    public const string Month = "Month";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        None,
        Year,
        Month,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
