// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>number_sequences.scope_key</c>, enforced by the database CHECK constraint
/// <c>ck_number_sequences__scope_key</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_number_sequences__scope_key
{
    public const string Table = "number_sequences";
    public const string Column = "scope_key";
    public const string ConstraintName = "ck_number_sequences__scope_key";
    public const bool NullAllowed = false;

    public const string employee_no = "employee_no";
    public const string letter_no = "letter_no";
    public const string run_no = "run_no";
    public const string wps_batch_no = "wps_batch_no";
    public const string settlement_no = "settlement_no";
    public const string gosi_filing_no = "gosi_filing_no";
    public const string timesheet_no = "timesheet_no";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        employee_no,
        letter_no,
        run_no,
        wps_batch_no,
        settlement_no,
        gosi_filing_no,
        timesheet_no,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
