// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>overtime_requests.ot_type</c>, enforced by the database CHECK constraint
/// <c>ck_overtime_requests__ot_type</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_overtime_requests__ot_type
{
    public const string Table = "overtime_requests";
    public const string Column = "ot_type";
    public const string ConstraintName = "ck_overtime_requests__ot_type";
    public const bool NullAllowed = false;

    public const string Normal = "Normal";
    public const string WeeklyOff = "WeeklyOff";
    public const string PublicHoliday = "PublicHoliday";
    public const string Ramadan = "Ramadan";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Normal,
        WeeklyOff,
        PublicHoliday,
        Ramadan,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
