// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>overtime_requests.payout</c>, enforced by the database CHECK constraint
/// <c>ck_overtime_requests__payout</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_overtime_requests__payout
{
    public const string Table = "overtime_requests";
    public const string Column = "payout";
    public const string ConstraintName = "ck_overtime_requests__payout";
    public const bool NullAllowed = false;

    public const string Pay = "Pay";
    public const string CompOff = "CompOff";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Pay,
        CompOff,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
