// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>payroll_inputs.target_run_type</c>, enforced by the database CHECK constraint
/// <c>ck_payroll_inputs__target_run_type</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// The column is nullable: NULL is permitted and is not a member of ck_payroll_inputs__target_run_type.All.
/// </summary>
public static class ck_payroll_inputs__target_run_type
{
    public const string Table = "payroll_inputs";
    public const string Column = "target_run_type";
    public const string ConstraintName = "ck_payroll_inputs__target_run_type";
    public const bool NullAllowed = true;

    public const string Regular = "Regular";
    public const string OffCycle = "OffCycle";
    public const string FinalSettlement = "FinalSettlement";
    public const string Correction = "Correction";
    public const string Opening = "Opening";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Regular,
        OffCycle,
        FinalSettlement,
        Correction,
        Opening,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
