// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>payroll_inputs.source_type</c>, enforced by the database CHECK constraint
/// <c>ck_payroll_inputs__source_type</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_payroll_inputs__source_type
{
    public const string Table = "payroll_inputs";
    public const string Column = "source_type";
    public const string ConstraintName = "ck_payroll_inputs__source_type";
    public const bool NullAllowed = false;

    public const string Overtime = "Overtime";
    public const string Leave = "Leave";
    public const string Attendance = "Attendance";
    public const string Timesheet = "Timesheet";
    public const string Manual = "Manual";
    public const string Opening = "Opening";
    public const string Bonus = "Bonus";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Overtime,
        Leave,
        Attendance,
        Timesheet,
        Manual,
        Opening,
        Bonus,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
