// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>payroll_inputs.kind</c>, enforced by the database CHECK constraint
/// <c>ck_payroll_inputs__kind</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_payroll_inputs__kind
{
    public const string Table = "payroll_inputs";
    public const string Column = "kind";
    public const string ConstraintName = "ck_payroll_inputs__kind";
    public const bool NullAllowed = false;

    public const string Adjustment = "Adjustment";
    public const string Arrears = "Arrears";
    public const string Receivable = "Receivable";
    public const string Overtime = "Overtime";
    public const string UnpaidLeave = "UnpaidLeave";
    public const string Absence = "Absence";
    public const string LeaveEncashment = "LeaveEncashment";
    public const string Bonus = "Bonus";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Adjustment,
        Arrears,
        Receivable,
        Overtime,
        UnpaidLeave,
        Absence,
        LeaveEncashment,
        Bonus,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
