// <auto-generated by Db/baseline; see KynexDomains.cs />
#nullable enable // the file's first line marks it generated, which turns the project's nullable context off
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>retention_purge_audits.disposition</c>, enforced by the database CHECK constraint
/// <c>ck_retention_purge_audits__disposition</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_retention_purge_audits__disposition
{
    public const string Table = "retention_purge_audits";
    public const string Column = "disposition";
    public const string ConstraintName = "ck_retention_purge_audits__disposition";
    public const bool NullAllowed = false;

    public const string Anonymise = "Anonymise";
    public const string Purge = "Purge";
    public const string Keep = "Keep";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Anonymise,
        Purge,
        Keep,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
