// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>retention_policies.trigger_event</c>, enforced by the database CHECK constraint
/// <c>ck_retention_policies__trigger_event</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_retention_policies__trigger_event
{
    public const string Table = "retention_policies";
    public const string Column = "trigger_event";
    public const string ConstraintName = "ck_retention_policies__trigger_event";
    public const bool NullAllowed = false;

    public const string SoftDelete = "SoftDelete";
    public const string Separation = "Separation";
    public const string RecordDate = "RecordDate";
    public const string Expiry = "Expiry";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        SoftDelete,
        Separation,
        RecordDate,
        Expiry,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
