// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>statutory_rules.cohort</c>, enforced by the database CHECK constraint
/// <c>ck_statutory_rules__cohort</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_statutory_rules__cohort
{
    public const string Table = "statutory_rules";
    public const string Column = "cohort";
    public const string ConstraintName = "ck_statutory_rules__cohort";
    public const bool NullAllowed = false;

    public const string Legacy = "Legacy";
    public const string Entrant2024 = "Entrant2024";
    public const string Any = "Any";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Legacy,
        Entrant2024,
        Any,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
