// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>statutory_rules.family</c>, enforced by the database CHECK constraint
/// <c>ck_statutory_rules__family</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_statutory_rules__family
{
    public const string Table = "statutory_rules";
    public const string Column = "family";
    public const string ConstraintName = "ck_statutory_rules__family";
    public const bool NullAllowed = false;

    public const string GOSI = "GOSI";
    public const string EOS = "EOS";
    public const string Overtime = "Overtime";
    public const string Leave = "Leave";
    public const string Nitaqat = "Nitaqat";
    public const string WPS = "WPS";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        GOSI,
        EOS,
        Overtime,
        Leave,
        Nitaqat,
        WPS,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
