// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>statutory_rules.nationality_class</c>, enforced by the database CHECK constraint
/// <c>ck_statutory_rules__nationality_class</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_statutory_rules__nationality_class
{
    public const string Table = "statutory_rules";
    public const string Column = "nationality_class";
    public const string ConstraintName = "ck_statutory_rules__nationality_class";
    public const bool NullAllowed = false;

    public const string Saudi = "Saudi";
    public const string GCC = "GCC";
    public const string NonSaudi = "NonSaudi";
    public const string Any = "Any";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Saudi,
        GCC,
        NonSaudi,
        Any,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
