// <auto-generated by Db/baseline; see KynexDomains.cs />
#pragma warning disable IDE1006 // the type name IS the constraint name
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Closed set behind <c>statutory_rule_bands.unit</c>, enforced by the database CHECK constraint
/// <c>ck_statutory_rule_bands__unit</c>. The class name is that constraint name verbatim — KynexDomainsTests
/// asserts the two are identical, so renaming this type breaks the build, not production.
/// </summary>
public static class ck_statutory_rule_bands__unit
{
    public const string Table = "statutory_rule_bands";
    public const string Column = "unit";
    public const string ConstraintName = "ck_statutory_rule_bands__unit";
    public const bool NullAllowed = false;

    public const string ServiceYears = "ServiceYears";
    public const string SickDays = "SickDays";
    public const string ContributoryWage = "ContributoryWage";

    /// <summary>Every legal value, in the order the CHECK declares them.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        ServiceYears,
        SickDays,
        ContributoryWage,
    };

    public static bool IsValid(string? value) => value is not null && All.Contains(value);
}
