// <auto-generated by Db/baseline; regenerate with scratchpad/gen_domains.py />
#pragma warning disable IDE1006
namespace Zayra.Api.Data.V2.Domains;

/// <summary>
/// Every closed set in the baseline schema, as (constraint name, table, column, values).
/// TARGET_SCHEMA.md SS9. The 37 <c>chk_*</c> names are the frozen legacy set (SS9.0: no
/// thirty-eighth is ever added); everything written from revision 7 onward is <c>ck_*</c>.
/// KynexDomainsTests compares this list against pg_constraint in a database built from
/// Db/baseline, so a CHECK that gains a value without its constants class fails CI.
/// </summary>
public static class KynexDomains
{
    public sealed record Domain(string ConstraintName, string Table, string Column, bool NullAllowed, IReadOnlyList<string> Values);

    public static readonly IReadOnlyList<Domain> All = new Domain[]
    {
        new("chk_approval_actions_action", "approval_actions", "action", false, chk_approval_actions_action.All),
        new("chk_approval_requests_status", "approval_requests", "status", false, chk_approval_requests_status.All),
        new("chk_attendance_days_status", "attendance_days", "status", false, chk_attendance_days_status.All),
        new("chk_auth_subject_kind_auth_sessions", "auth_sessions", "subject_kind", false, chk_auth_subject_kind_auth_sessions.All),
        new("chk_auth_subject_kind_auth_tokens", "auth_tokens", "subject_kind", false, chk_auth_subject_kind_auth_tokens.All),
        new("chk_auth_tokens_purpose", "auth_tokens", "purpose", false, chk_auth_tokens_purpose.All),
        new("chk_background_job_items_status", "background_job_items", "status", false, chk_background_job_items_status.All),
        new("chk_background_jobs_status", "background_jobs", "status", false, chk_background_jobs_status.All),
        new("chk_egr_status", "employee_gosi_registrations", "status", false, chk_egr_status.All),
        new("chk_employee_documents_status", "employee_documents", "status", false, chk_employee_documents_status.All),
        new("chk_employee_documents_type", "employee_documents", "doc_type", false, chk_employee_documents_type.All),
        new("chk_employees_privacy", "employees", "privacy_status", false, chk_employees_privacy.All),
        new("chk_employees_status", "employees", "status", false, chk_employees_status.All),
        new("chk_eos_calculations_status", "eos_calculations", "status", false, chk_eos_calculations_status.All),
        new("chk_files_purge_state", "files", "purge_state", false, chk_files_purge_state.All),
        new("chk_final_settlements_status", "final_settlements", "status", false, chk_final_settlements_status.All),
        new("chk_gl_journals_status", "gl_journals", "status", false, chk_gl_journals_status.All),
        new("chk_gl_period_closes_status", "gl_period_closes", "status", false, chk_gl_period_closes_status.All),
        new("chk_gosi_filings_status", "gosi_filings", "status", false, chk_gosi_filings_status.All),
        new("chk_leave_requests_status", "leave_requests", "status", false, chk_leave_requests_status.All),
        new("chk_loan_installments_status", "loan_installments", "status", false, chk_loan_installments_status.All),
        new("chk_loans_status", "loans", "status", false, chk_loans_status.All),
        new("chk_notification_deliveries_status", "notification_deliveries", "status", false, chk_notification_deliveries_status.All),
        new("chk_overtime_requests_status", "overtime_requests", "status", false, chk_overtime_requests_status.All),
        new("chk_payroll_inputs_status", "payroll_inputs", "status", false, chk_payroll_inputs_status.All),
        new("chk_payroll_issues_severity", "payroll_issues", "severity", false, chk_payroll_issues_severity.All),
        new("chk_payroll_runs_status", "payroll_runs", "status", false, chk_payroll_runs_status.All),
        new("chk_payroll_runs_type", "payroll_runs", "run_type", false, chk_payroll_runs_type.All),
        new("chk_payroll_slip_lines_kind", "payroll_slip_lines", "kind", false, chk_payroll_slip_lines_kind.All),
        new("chk_payroll_slips_inclusion", "payroll_slips", "inclusion_status", false, chk_payroll_slips_inclusion.All),
        new("chk_platform_users_status", "platform_users", "status", false, chk_platform_users_status.All),
        new("chk_retention_policies_disposition", "retention_policies", "disposition", false, chk_retention_policies_disposition.All),
        new("chk_tenants_status", "tenants", "status", false, chk_tenants_status.All),
        new("chk_timesheets_status", "timesheets", "status", false, chk_timesheets_status.All),
        new("chk_tsdr_status", "timesheet_day_reconciliations", "status", false, chk_tsdr_status.All),
        new("chk_users_status", "users", "status", false, chk_users_status.All),
        new("chk_wps_batches_status", "wps_batches", "status", false, chk_wps_batches_status.All),
        new("chk_wps_lines_bank_status", "wps_lines", "bank_status", false, chk_wps_lines_bank_status.All),
        new("ck_approval_requests__request_type", "approval_requests", "request_type", false, ck_approval_requests__request_type.All),
        new("ck_approval_requests__subject_type", "approval_requests", "subject_type", false, ck_approval_requests__subject_type.All),
        new("ck_approval_workflows__request_type", "approval_workflows", "request_type", false, ck_approval_workflows__request_type.All),
        new("ck_attendance_punches__direction", "attendance_punches", "direction", false, ck_attendance_punches__direction.All),
        new("ck_attendance_punches__source", "attendance_punches", "source", false, ck_attendance_punches__source.All),
        new("ck_audit_logs__category", "audit_logs", "category", true, ck_audit_logs__category.All),
        new("ck_audit_logs__record_kind", "audit_logs", "record_kind", false, ck_audit_logs__record_kind.All),
        new("ck_document_templates__kind", "document_templates", "kind", false, ck_document_templates__kind.All),
        new("ck_eos_calculations__separation_reason", "eos_calculations", "separation_reason", false, ck_eos_calculations__separation_reason.All),
        new("ck_files__purpose", "files", "purpose", false, ck_files__purpose.All),
        new("ck_final_settlement_lines__kind", "final_settlement_lines", "kind", false, ck_final_settlement_lines__kind.All),
        new("ck_final_settlements__separation_type", "final_settlements", "separation_type", false, ck_final_settlements__separation_type.All),
        new("ck_gl_journals__source_type", "gl_journals", "source_type", false, ck_gl_journals__source_type.All),
        new("ck_leave_ledger__entry_type", "leave_ledger", "entry_type", false, ck_leave_ledger__entry_type.All),
        new("ck_leave_requests__request_kind", "leave_requests", "request_kind", false, ck_leave_requests__request_kind.All),
        new("ck_loan_installments__kind", "loan_installments", "kind", false, ck_loan_installments__kind.All),
        new("ck_loans__kind", "loans", "kind", false, ck_loans__kind.All),
        new("ck_nitaqat_grid__band", "nitaqat_grid", "band", false, ck_nitaqat_grid__band.All),
        new("ck_nitaqat_snapshots__band", "nitaqat_snapshots", "band", false, ck_nitaqat_snapshots__band.All),
        new("ck_notification_deliveries__channel", "notification_deliveries", "channel", false, ck_notification_deliveries__channel.All),
        new("ck_number_sequences__reset_period", "number_sequences", "reset_period", false, ck_number_sequences__reset_period.All),
        new("ck_number_sequences__scope_key", "number_sequences", "scope_key", false, ck_number_sequences__scope_key.All),
        new("ck_overtime_requests__ot_type", "overtime_requests", "ot_type", false, ck_overtime_requests__ot_type.All),
        new("ck_overtime_requests__payout", "overtime_requests", "payout", false, ck_overtime_requests__payout.All),
        new("ck_pay_components__kind", "pay_components", "kind", false, ck_pay_components__kind.All),
        new("ck_payroll_inputs__kind", "payroll_inputs", "kind", false, ck_payroll_inputs__kind.All),
        new("ck_payroll_inputs__source_type", "payroll_inputs", "source_type", false, ck_payroll_inputs__source_type.All),
        new("ck_payroll_inputs__target_run_type", "payroll_inputs", "target_run_type", true, ck_payroll_inputs__target_run_type.All),
        new("ck_retention_policies__trigger_event", "retention_policies", "trigger_event", false, ck_retention_policies__trigger_event.All),
        new("ck_retention_purge_audits__disposition", "retention_purge_audits", "disposition", false, ck_retention_purge_audits__disposition.All),
        new("ck_retention_purge_audits__outcome", "retention_purge_audits", "outcome", false, ck_retention_purge_audits__outcome.All),
        new("ck_statutory_rule_bands__unit", "statutory_rule_bands", "unit", false, ck_statutory_rule_bands__unit.All),
        new("ck_statutory_rules__cohort", "statutory_rules", "cohort", false, ck_statutory_rules__cohort.All),
        new("ck_statutory_rules__family", "statutory_rules", "family", false, ck_statutory_rules__family.All),
        new("ck_statutory_rules__nationality_class", "statutory_rules", "nationality_class", false, ck_statutory_rules__nationality_class.All),
    };

    /// <summary>
    /// TARGET_SCHEMA.md revision 7 SS9 rows 37 and 38, which the baseline DDL has not declared.
    /// The columns exist (statutory_rules.gosi_branch / .payer, payroll_slip_lines.gosi_branch /
    /// .gosi_payer) and are unconstrained varchar today. These four are kept here, out of
    /// <see cref="All"/>, so the gap is a named fact rather than a missing file; KynexDomainsTests
    /// asserts each one either is absent from pg_constraint or matches it exactly, so declaring
    /// the constraint in 020/021 needs no change here beyond moving the row up.
    /// </summary>
    public static readonly IReadOnlyList<Domain> DesignedButNotYetConstrained = new Domain[]
    {
        new("ck_statutory_rules__gosi_branch", "statutory_rules", "gosi_branch", true, ck_statutory_rules__gosi_branch.All),
        new("ck_payroll_slip_lines__gosi_branch", "payroll_slip_lines", "gosi_branch", true, ck_payroll_slip_lines__gosi_branch.All),
        new("ck_statutory_rules__payer", "statutory_rules", "payer", true, ck_statutory_rules__payer.All),
        new("ck_payroll_slip_lines__gosi_payer", "payroll_slip_lines", "gosi_payer", true, ck_payroll_slip_lines__gosi_payer.All),
    };
}
