namespace Zayra.Api.Infrastructure.Payroll;

// ─────────────────────────────────────────────────────────────────────────────
//  What the wage file IS, and what it is NOT.
//
//  THE HOLE THIS CLOSES. SifFileGenerator's own header comment says the Saudi
//  Mudad/SAMA field widths, segment identifiers and encoding "have NOT been
//  independently confirmed against a live Mudad acceptance test", and asks whoever
//  reads it to check the generated file against the published MHRSD specification
//  before submitting. That comment is true, it is load-bearing, and it is NOT
//  deleted by this change. What changed is that somebody finally did the check it
//  asked for.
//
//  ── THE CHECK, AND ITS RESULT ───────────────────────────────────────────────
//  SOURCE: "Wages Protection System — WPS Wages File Specification", Ministry of
//  Human Resources and Social Development (MHRSD, then Ministry of Labour),
//  published at
//    https://www.hrsd.gov.sa/sites/default/files/2017-06/WPS%20Wages%20File%20Technical%20Specification.pdf
//  Retrieved and text-extracted 2026-09-20. 21 pages, MD5 392f62cbb9a3eec39c7137d0974c988a.
//  PDF creation date 2015-09-07; it is the only Saudi WPS file specification
//  published openly, and it predates the Mudad platform (launched December 2020).
//
//  Against that specification the generated file does not conform, and the gap is
//  not a matter of field widths:
//
//   1. DELIMITING MODEL. The spec (§1.4(2), §1.7(2)) requires a TAB-delimited
//      .txt file. This generator emits fixed-width fields joined by "+" and
//      terminated by "'". Neither character appears anywhere in the spec.
//   2. RECORD IDENTIFIERS. The spec has no record-type prefixes at all; it uses
//      bracketed SWIFT-style FIELD tags ([DEST-ID], [32A-AMT], [MOL-BAS] …).
//      "EDI_DC40" and "E1EDL20" are SAP IDoc structures — EDI_DC40 is the IDoc
//      control record and E1EDL20 is a DELIVERY-HEADER segment from SAP logistics.
//      A string search of the extracted spec finds ZERO occurrences of "EDI",
//      "E1ED", "IDoc", "SIF" or "XML". They are also absent from the UAE CBUAE
//      SIF format this layout was said to be adapted from.
//   3. MISSING MANDATORY FIELDS. The spec requires the wage BREAKDOWN per
//      employee — [MOL-BAS] basic, [MOL-HAL] housing, [MOL-OEA] other earnings,
//      [MOL-DED] deductions, [MOL-ID] government ID, [59-NAME] beneficiary name —
//      plus a header carrying [DEST-ID], [BANK-ACC] and [FILE-REF]. This file
//      emits net pay only. Matching those wage components against GOSI is the
//      entire purpose of the submission, so a net-pay-only file could not serve it
//      even if the syntax were right.
//   4. DECIMAL SEPARATOR. The spec states "Valid Format is 1234567890123,12" — a
//      COMMA. This generator formats with "F2", which emits a point.
//   5. CURRENCY. The spec carries currency once, in the header ([32A-CCY]). This
//      file repeats it on every detail line.
//
//  ── AND A STRUCTURAL POINT THAT NO LAYOUT FIX WOULD ANSWER ──────────────────
//  In Saudi Arabia the WPS file is produced BY THE EMPLOYER'S BANK, not by the
//  payroll system. The spec puts the establishment→bank transfer explicitly out of
//  scope ("Transfer of Wages file from Establishment(s) to Bank(s) — Not related to
//  WPS proposed process, out of scope for WPS", §2), and the file the employer
//  finally uploads carries the BANK's digital signature (SHA1withRSA, §3.3.1),
//  which Mudad validates against a public key it holds. MHRSD's own establishment
//  user guide tells employers not even to OPEN the bank's file, because doing so
//  breaks the signature. A file generated here has no such signature and there is
//  no path by which it could acquire one.
//
//  So the honest position is not "unverified layout". It is: this is a PROPRIETARY
//  INTERNAL EXPORT. It is fit for handing to a bank or reviewing internally; it is
//  not a Saudi WPS submission and cannot be made into one by changing bytes.
//
//  WHY THE GENERATOR IS NOT RIPPED OUT HERE. Deleting the export would take a
//  working operational artefact away from customers who use it to instruct their
//  bank, and re-pointing the product at the real integration surfaces (per-bank
//  payroll instruction formats, or Mudad PMS partner integration) is a product and
//  procurement decision with a commercial dependency — a Mudad subscription, a
//  bank channel, an authorised signatory. That decision belongs to the product
//  owner and is written up for them. What engineering can do today, and does here,
//  is stop the product from claiming something the file cannot support.
//
//  This type does NOT change the generated bytes. The file is content-addressed by
//  SHA-256 and its determinism is pinned by tests, so the statement travels beside
//  the artefact — API responses and a response header on the download.
// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// Machine-readable statement of what a generated wage artefact is, what has been verified about
/// it, and what it is not. Attached to the validation result, the generate response, and the
/// download.
/// </summary>
public sealed record WpsConformanceStatement(
    string FormatVersion,
    // Short enough for a badge. One of the Levels below.
    string Level,
    // One sentence that can be read aloud to an evaluator without it later turning out to be false.
    string Headline,
    // Precisely what IS true of this file.
    IReadOnlyList<string> Verified,
    // Precisely what is NOT. Never empty.
    IReadOnlyList<string> NotVerified,
    // False until a real gateway has accepted a file from this generator. See the notes above for
    // why, in Saudi Arabia specifically, it cannot become true without a different design.
    bool AcceptedByLiveGateway,
    // True when the layout has been compared to a published specification, whatever the outcome.
    bool CheckedAgainstPublishedSpecification,
    string SpecificationChecked,
    string SpecificationUrl,
    string SpecificationCheckedOn,
    // The exact next step, and whose job it is.
    string RemediationOwner,
    string Remediation);

public static class WpsConformance
{
    public static class Levels
    {
        /// <summary>
        /// Contents validated against the payroll run, but the artefact is a proprietary internal
        /// export that does not conform to the published Saudi WPS specification and is not a WPS
        /// submission.
        /// </summary>
        public const string ProprietaryExportNotWpsConformant = "proprietary-export-not-wps-conformant";

        /// <summary>A real gateway has accepted a file from this generator. Nothing is at this level.</summary>
        public const string GatewayAccepted = "gateway-accepted";
    }

    /// <summary>
    /// Header name on the file download. A header rather than a change to the file body: the bytes
    /// are hashed and the hash is stored on WPSFileBatch, so anything added to the payload would
    /// break content addressing and every determinism test that depends on it.
    /// </summary>
    public const string DownloadHeader = "X-Wps-Conformance";

    public const string SpecTitle =
        "MHRSD 'Wages Protection System — WPS Wages File Specification' (21pp, PDF created 2015-09-07; "
        + "the only openly published Saudi WPS file specification, predating the Mudad platform)";

    public const string SpecUrl =
        "https://www.hrsd.gov.sa/sites/default/files/2017-06/WPS%20Wages%20File%20Technical%20Specification.pdf";

    /// <summary>Date the specification was retrieved and the comparison performed.</summary>
    public const string SpecCheckedOn = "2026-09-20";

    /// <summary>
    /// What <see cref="WpsSifValidator"/> and the generator genuinely guarantee. Stated as
    /// capabilities rather than as "validated", because "the file is validated" is precisely the
    /// sentence that misleads: the validator checks the DATA, never the FORMAT.
    /// </summary>
    private static readonly string[] ValidatorGuarantees =
    {
        "Every payslip in the run resolves to exactly one employee (no duplicates).",
        "Every net pay is positive and every gross is non-negative, and the run header total "
            + "reconciles to the sum of the payslips.",
        "Every employee has an IBAN that passes the ISO 13616 mod-97 check and the country "
            + "length rule; a non-Saudi IBAN is surfaced as a warning.",
        "No employee who could never have been payable (never activated, or fully closed out) is "
            + "in the file, and no WPS-ineligible payroll profile is in it.",
        "Every employee carries the government ID number wage reporting requires, and anyone "
            + "failing the statutory readiness check is blocked.",
        "Generation is deterministic: the same payment batch always produces byte-identical output "
            + "and therefore the same SHA-256, so a re-issued file can be proved identical to the "
            + "one that was approved.",
    };

    /// <summary>
    /// The honest negative, itemised. Kept as specific as the positive list, because a vague
    /// disclaimer reads as boilerplate and gets ignored. Every line here is checkable against the
    /// specification named above.
    /// </summary>
    private static readonly string[] NotConformant =
    {
        "THIS IS NOT A SAUDI WPS FILE. Compared against the published MHRSD WPS Wages File "
            + "Specification on " + SpecCheckedOn + ", the layout does not conform.",
        "The specification requires a TAB-delimited UTF-8 .txt file with bracketed SWIFT-style "
            + "field tags ([DEST-ID], [32A-AMT], [MOL-BAS] …). This export emits fixed-width fields "
            + "joined by '+' and terminated by \"'\"; neither character appears in the specification.",
        "'EDI_DC40' and 'E1EDL20' are SAP IDoc structures — the IDoc control record and a logistics "
            + "delivery-header segment. They appear nowhere in the Saudi specification, nor in the "
            + "UAE CBUAE SIF format this layout was said to be adapted from.",
        "The specification requires the per-employee wage BREAKDOWN — basic [MOL-BAS], housing "
            + "[MOL-HAL], other earnings [MOL-OEA], deductions [MOL-DED], government ID [MOL-ID] and "
            + "beneficiary name [59-NAME]. This export carries net pay only, so it could not serve "
            + "the GOSI wage matching that is the submission's purpose even with correct syntax.",
        "The specification's amount format uses a COMMA decimal separator ('1234567890123,12'); "
            + "this export writes a point.",
        "STRUCTURALLY, a payroll system cannot produce a Saudi WPS file at all. The employer→bank "
            + "transfer is explicitly out of scope of the specification; the file the employer "
            + "uploads to Mudad is produced and digitally signed by the BANK (SHA1withRSA) and "
            + "Mudad validates that signature. MHRSD's guidance tells employers not even to open "
            + "the bank's file. No file generated here can acquire that signature.",
        "No file from this generator has been submitted to, or accepted by, Mudad, MHRSD, GOSI or "
            + "any Saudi bank.",
        "The validator checks the DATA in the file. It does not — and structurally cannot — check "
            + "that the FORMAT is one a gateway will parse.",
    };

    /// <summary>
    /// Conformance for the wage-export path. <paramref name="formatVersion"/> is whatever the
    /// country-pack exporter actually produced (e.g. SIF_SA_V1, mudad-xml), so the statement cannot
    /// drift from the artefact it describes.
    /// </summary>
    public static WpsConformanceStatement For(string? formatVersion) => new(
        FormatVersion: string.IsNullOrWhiteSpace(formatVersion)
            ? SifFileGenerator.FormatVersion
            : formatVersion,
        Level: Levels.ProprietaryExportNotWpsConformant,
        Headline:
            "Proprietary payroll export — NOT a Saudi WPS file. Its contents have been checked "
            + "against the payroll run, and its layout has been checked against the published MHRSD "
            + "WPS specification and does not conform. In Saudi Arabia the WPS file is generated and "
            + "digitally signed by the employer's BANK from the payroll instruction you send it, and "
            + "uploaded to Mudad. Use this file to instruct your bank or to review the run — never "
            + "as a wage-protection submission.",
        Verified: ValidatorGuarantees,
        NotVerified: NotConformant,
        AcceptedByLiveGateway: false,
        CheckedAgainstPublishedSpecification: true,
        SpecificationChecked: SpecTitle,
        SpecificationUrl: SpecUrl,
        SpecificationCheckedOn: SpecCheckedOn,
        RemediationOwner:
            "Product owner / commercial — engineering cannot close this. It needs a bank "
            + "relationship or a Mudad subscription, not code.",
        Remediation:
            "Two real routes exist, and both are procurement before they are engineering. "
            + "(a) PER-BANK PAYROLL INSTRUCTION: ask a pilot customer's bank cash-management team "
            + "for its payroll-file format, build that export, and have the bank return its signed "
            + "WPS file for the customer to upload to Mudad. The employer→bank format is set by "
            + "each bank individually and is outside the MHRSD specification, so this must be "
            + "agreed bank by bank. (b) MUDAD PMS PARTNER INTEGRATION: apply to Mudad as an "
            + "integration partner. There is no public Mudad API specification or sandbox; access "
            + "is gated on a Mudad subscription, an authorised signatory, a Mudad-connected bank "
            + "channel and GOSI name matching. Until one of these exists, the product must say "
            + "'payroll export', never 'WPS submission'.");

    /// <summary>
    /// One-line form for the download response header, which cannot carry structured JSON legibly.
    /// Deliberately blunt: this is the last thing a customer sees before the bytes.
    /// </summary>
    public static string HeaderValue(string? formatVersion) =>
        $"level={Levels.ProprietaryExportNotWpsConformant}; "
        + $"format={(string.IsNullOrWhiteSpace(formatVersion) ? SifFileGenerator.FormatVersion : formatVersion)}; "
        + "accepted-by-live-gateway=false; wps-conformant=false; "
        + $"checked-against-spec={SpecCheckedOn}; "
        + "note=\"Proprietary payroll export. Contents validated against the payroll run. Layout "
        + "checked against the published MHRSD WPS Wages File Specification and does NOT conform. "
        + "In Saudi Arabia the WPS file is produced and digitally signed by the employer's bank. "
        + "This file is not a wage-protection submission.\"";
}
