using Zayra.Api.Models;

namespace Zayra.Api.Infrastructure.Payroll;

/// <summary>
/// Validates a payroll run for WPS/SIF export eligibility.
///
/// Returns <see cref="WpsValidationResult"/> with two categories:
///   <c>BlockingErrors</c> — must all be resolved before export is allowed.
///   <c>Warnings</c>       — informational; do not block export.
///
/// The same rules are enforced server-side inside the export endpoint so
/// the validator is never the sole enforcement point.
///
/// <para><b>WHAT "VALID" MEANS HERE, AND WHAT IT DOES NOT.</b> Every rule below is about the DATA
/// in the file: who is in it, whether their IBAN is well-formed, whether the totals reconcile,
/// whether anyone in it should not be paid. Not one rule is about the FILE FORMAT, and this class
/// structurally cannot check one — it never sees the generated bytes. So "0 blocking errors" means
/// "the payroll data is fit to pay", not "a Saudi WPS gateway will accept this submission".</para>
///
/// <para>That distinction matters because <see cref="SifFileGenerator"/> states, correctly, that
/// the Saudi field widths and segment identifiers have never been confirmed against a live Mudad
/// acceptance test. An operator who reads a green validation result and concludes the filing is
/// safe has been misled by this class's name. <see cref="WpsConformance"/> is the statement of
/// exactly this scope, and it is attached to the validation response, the generate response and
/// the file download so the operator sees it where the decision is made.</para>
/// </summary>
public static class WpsSifValidator
{
    private static readonly IReadOnlySet<string> ExportableRunStatuses =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "Approved", "Locked", "Paid",
        };

    /// <summary>
    /// S2-B1 — statuses for which a payslip in the run is a DATA ERROR, never a payment: the employment
    /// relationship either never began or is fully closed out, so no wage can be owed.
    ///
    /// <para><b>WHY THIS SET SHRANK, AND WHAT IT COST BEFORE.</b> It used to contain <c>Offboarded</c> and
    /// <c>Suspended</c> as well, and membership is a BLOCKING error. But
    /// <c>OffboardingController.Initiate</c> sets <c>Employee.Status = "Offboarded"</c> at NOTICE time —
    /// the person is still employed, still in headcount, and <c>PayrollController</c>'s
    /// <c>LoadEligibleWithLeaversAsync</c> exists precisely to keep paying them through their last working
    /// day (POD-C3 fixed the defect where "from the day a resignation was keyed, the employee vanished
    /// from every payroll run and was paid NOTHING"). Payroll therefore computed their pay and this
    /// validator then refused the wage file that delivers it. One notice-server blocked the WHOLE file,
    /// and for a 200-person establishment that is most months. Non-submission of the WPS/SIF is an MOL
    /// violation that can freeze the establishment's Qiwa services, so the two fixes cancelled out into
    /// something worse than either defect alone.</para>
    ///
    /// <para><b>SUSPENDED IS PAID, AND THE OLD COMMENT HERE WAS WRONG.</b> This file used to assert that
    /// "a Suspended employee's pay is legally on hold". It is not.
    /// <c>Application/Organization/EstablishmentOccupancy</c> states the correct position, and the two
    /// files contradicted each other: under KSA Labour Law Arts. 66–68 a suspension is a CONTINUING,
    /// GOSI-registered employment relationship, and Art. 67 obliges the employer to keep paying the worker
    /// pending the outcome of the investigation. Withholding a suspended worker's wage — which is what
    /// blocking the wage file does — is the violation, not the safeguard. Occupancy and the wage file now
    /// read the status the same way.</para>
    ///
    /// <para><b>TERMINATED IS NOT TERMINAL EITHER.</b> A recorded termination still owes a final wage month
    /// and a settlement; <c>Archived</c> (offboarding COMPLETED) is the close-out. The precise per-person
    /// "never pay this profile again" gate is <c>EmployeePayrollProfile.WpsEligible</c>, which the exit
    /// cascade clears on completion and which is checked independently below. This status set is the crude
    /// backstop for rows that could never have been payable at all.</para>
    /// </summary>
    private static readonly IReadOnlySet<string> TerminalEmployeeStatuses =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            // Never activated — no employment relationship ever existed.
            "Draft", "Invited",
            // Fully closed out — offboarding completed / legacy dormant.
            "Archived", "Exited", "Inactive",
        };

    /// <summary>
    /// S2-B1 — still-employed statuses that are PAYABLE but worth surfacing, so the operator can see who
    /// is in the file and why without the file ever being refused. A warning never sets
    /// <see cref="WpsValidationResult.CanExport"/> to false.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, (string Code, string Why)> PayableSeparationStatuses =
        new Dictionary<string, (string, string)>(StringComparer.OrdinalIgnoreCase)
        {
            ["Offboarded"] = ("EMPLOYEE_SERVING_NOTICE",
                "is serving notice. They remain employed until their last working day and their wage is due in full."),
            ["Suspended"]  = ("EMPLOYEE_SUSPENDED",
                "is suspended. Under KSA Labour Law Arts. 66–68 the employment relationship continues and Art. 67 requires pay to continue pending the outcome."),
            ["Terminated"] = ("EMPLOYEE_SEPARATION_RECORDED",
                "has a recorded separation that has not been closed out. Their final wage month and settlement are still payable."),
        };

    /// <summary>
    /// Validates the payroll run + its slips + employee profiles + employee master data
    /// and returns a full validation result.
    ///
    /// <paramref name="payBlockedEmployeeIds"/> is the readiness pay-block set — computed by the CALLER
    /// via the ONE readiness evaluator (missing GOSI/social-insurance ref, expired Iqama/visa/EID/QID/CivilId
    /// at pay date, missing MolId/routing where required, State==Blocked). The validator stays PURE: it
    /// simply turns membership into a blocking error so activation and pay read the same evaluator.
    /// </summary>
    public static WpsValidationResult Validate(
        PayrollRun                       run,
        IReadOnlyList<PayrollSlip>       slips,
        IReadOnlyList<EmployeePayrollProfile> profiles,
        IReadOnlyList<Employee>          employees,
        IReadOnlySet<int>?               payBlockedEmployeeIds = null)
    {
        var errors   = new List<WpsValidationIssue>();
        var warnings = new List<WpsValidationIssue>();

        // ── Run-level checks ─────────────────────────────────────────────────

        if (!ExportableRunStatuses.Contains(run.Status))
            errors.Add(RunError("RUN_NOT_APPROVED",
                $"Payroll run status is '{run.Status}'. Run must be Approved (or Locked/Paid) before WPS export."));

        if (slips.Count == 0)
            errors.Add(RunError("NO_PAYROLL_ROWS",
                "No payroll slips found for this run. Process the run before exporting."));

        // Total mismatch: run header vs sum of slips
        if (slips.Count > 0)
        {
            var slipTotal = slips.Sum(s => s.NetSalary);
            if (run.TotalNetSalary != 0 && Math.Abs(run.TotalNetSalary - slipTotal) > 0.01m)
                errors.Add(RunError("TOTAL_MISMATCH",
                    $"Run total net salary ({run.TotalNetSalary:F2}) does not match the sum of payslips ({slipTotal:F2}). Re-process the run to recalculate totals."));
        }

        // ── Employee-level checks ────────────────────────────────────────────

        var seenEmployees = new HashSet<int>();

        foreach (var slip in slips)
        {
            var empId   = slip.EmployeeId;
            var empCode = slip.EmployeeCode;

            // Duplicate employee in the same run
            if (!seenEmployees.Add(empId))
            {
                errors.Add(EmpError("DUPLICATE_EMPLOYEE", empId, empCode,
                    $"Employee {empCode} appears more than once in this payroll run."));
                continue; // skip further checks for the duplicate row
            }

            // Salary amount checks
            if (slip.NetSalary <= 0)
                errors.Add(EmpError("INVALID_NET_SALARY", empId, empCode,
                    $"Employee {empCode} has a non-positive net salary ({slip.NetSalary:F2}). Correct the payroll data before exporting."));

            if (slip.GrossSalary < 0)
                errors.Add(EmpError("NEGATIVE_GROSS_SALARY", empId, empCode,
                    $"Employee {empCode} has a negative gross salary ({slip.GrossSalary:F2})."));

            // IBAN checks
            var profile = profiles.FirstOrDefault(p => p.EmployeeId == empId);
            var iban    = profile?.Iban;

            if (string.IsNullOrWhiteSpace(iban))
                errors.Add(EmpError("MISSING_IBAN", empId, empCode,
                    $"Employee {empCode} has no IBAN on their payroll profile. Add bank details before exporting."));
            else if (!IbanValidator.IsValid(iban))
                errors.Add(EmpError("INVALID_IBAN", empId, empCode,
                    $"Employee {empCode} has an invalid IBAN (country format/length or ISO 13616 mod-97 check failed)."));
            else if (!IbanValidator.IsSaudiIban(iban))
                warnings.Add(EmpWarning("NON_SAUDI_IBAN", empId, empCode,
                    $"Employee {empCode} IBAN does not start with 'SA'. Confirm the bank account is in Saudi Arabia."));

            // WpsEligible is now LOAD-BEARING (honours the exit cascade's WpsEligible=false): an
            // ineligible profile can never reach a wage file, independent of any other check.
            if (profile is not null && !profile.WpsEligible)
                errors.Add(EmpError("WPS_INELIGIBLE", empId, empCode,
                    $"Employee {empCode} is marked WPS-ineligible (e.g. separated / exit cascade). They cannot be included in a WPS export."));

            // Readiness pay-block: the ONE evaluator's verdict (missing/expired statutory details, State==Blocked).
            if (payBlockedEmployeeIds is not null && payBlockedEmployeeIds.Contains(empId))
                errors.Add(EmpError("READINESS_PAY_BLOCKED", empId, empCode,
                    $"Employee {empCode} is not payroll-ready — required statutory details are missing or expired. Complete their readiness checklist before exporting."));

            // Identity/master-data checks
            var emp = employees.FirstOrDefault(e => e.Id == empId);
            if (emp is null)
            {
                warnings.Add(EmpWarning("EMPLOYEE_NOT_IN_MASTER", empId, empCode,
                    $"Employee {empCode} payslip exists but no master employee record was found."));
            }
            else
            {
                if (string.IsNullOrWhiteSpace(emp.IdNumber))
                    errors.Add(EmpError("MISSING_ID_NUMBER", empId, empCode,
                        $"Employee {empCode} is missing a government ID number required for WPS regulatory reporting."));

                // A row that could never have been payable (never activated, or fully closed out) is a
                // BLOCKING error: it is a data defect, not a payment.
                if (TerminalEmployeeStatuses.Contains(emp.Status))
                    errors.Add(EmpError("INACTIVE_EMPLOYEE", empId, empCode,
                        $"Employee {empCode} has status '{emp.Status}' and cannot be included in a WPS export."));
                // S2-B1: a still-employed leaver/suspended worker IS payable. Surfaced so the file's
                // composition is visible, never blocked — blocking it withholds a wage that is legally due
                // and refuses the whole establishment's monthly submission because of one person.
                else if (PayableSeparationStatuses.TryGetValue(emp.Status, out var payable))
                    warnings.Add(EmpWarning(payable.Code, empId, empCode,
                        $"Employee {empCode} {payable.Why} Included in this wage file."));
            }
        }

        return new WpsValidationResult(errors, warnings);
    }

    // ── Issue factory helpers ─────────────────────────────────────────────────

    private static WpsValidationIssue RunError(string code, string message) =>
        new(code, message, null, null, WpsValidationScope.Run, true);

    private static WpsValidationIssue EmpError(string code, int empId, string empCode, string message) =>
        new(code, message, empId, empCode, WpsValidationScope.Employee, true);

    private static WpsValidationIssue EmpWarning(string code, int empId, string empCode, string message) =>
        new(code, message, empId, empCode, WpsValidationScope.Employee, false);
}

// ── Result types ─────────────────────────────────────────────────────────────

/// <summary>Scope of a validation issue.</summary>
public enum WpsValidationScope { Run, Employee, Bank }

/// <summary>A single validation issue from <see cref="WpsSifValidator"/>.</summary>
public record WpsValidationIssue(
    string             Code,
    string             Message,
    int?               EmployeeId,
    string?            EmployeeCode,
    WpsValidationScope Scope,
    bool               IsBlocking
);

/// <summary>
/// Full result from <see cref="WpsSifValidator.Validate"/>.
/// <c>CanExport</c> is <c>true</c> only when there are no blocking errors.
/// </summary>
public record WpsValidationResult(
    IReadOnlyList<WpsValidationIssue> BlockingErrors,
    IReadOnlyList<WpsValidationIssue> Warnings
)
{
    public bool CanExport     => BlockingErrors.Count == 0;
    public int  IssueCount    => BlockingErrors.Count + Warnings.Count;
    public int  WarningCount  => Warnings.Count;
    public int  ErrorCount    => BlockingErrors.Count;
}
