using Microsoft.Extensions.Logging;

namespace Zayra.Api.Infrastructure.Qiwa;

/// <summary>
/// In-memory mock of the Qiwa API used when no live credentials are configured
/// (environment = "sandbox") or when QIWA_USE_LIVE_ADAPTER is not "true".
///
/// It makes NO network calls.  Valid payloads return success; payloads with any
/// empty required field return a FIELD_MISSING error — mirroring real Qiwa
/// validation so the sync worker / retry logic can be exercised end-to-end.
///
/// <para><b>IT ANNOUNCES ITSELF.</b> Every response body this adapter produces carries
/// <c>"simulated": true</c> and <c>"filed_with_qiwa": false</c>, and
/// <see cref="IsLiveIntegration"/> is false, so the worker records a <c>Simulated</c>
/// outcome rather than <c>Synced</c>. Nothing here may ever produce a payload that is
/// indistinguishable from a real Qiwa acknowledgement: the stored
/// <c>QiwaSyncLog.ResponsePayloadJson</c> is evidence a customer may later be asked to
/// produce, and evidence that claims a filing which never happened is the worst
/// artefact this module could emit.</para>
/// </summary>
public sealed class SandboxQiwaApiAdapter : IQiwaApiAdapter
{
    /// <summary>
    /// Marker present in EVERY sandbox response body. Asserted by
    /// <c>MobilePushEnablement</c>-style honesty tests and greppable in support tickets.
    /// </summary>
    public const string SimulationMarker = "\"simulated\":true";

    private readonly ILogger<SandboxQiwaApiAdapter> _log;

    public SandboxQiwaApiAdapter(ILogger<SandboxQiwaApiAdapter> log) => _log = log;

    public string AdapterName => "sandbox";

    /// <summary>Never live. This adapter makes no network call of any kind.</summary>
    public bool IsLiveIntegration => false;

    public Task<string?> AcquireAccessTokenAsync(string clientId, string clientSecret, string environment, CancellationToken ct)
    {
        // Sandbox never needs real auth; return a synthetic token. The token is prefixed
        // "sandbox-" so that anything which ever logs or stores it is self-describing.
        if (string.Equals(environment, "production", StringComparison.OrdinalIgnoreCase))
            _log.LogWarning(
                "Qiwa connection requests environment 'production' but this process is running the "
                + "SANDBOX adapter (QIWA_USE_LIVE_ADAPTER is not 'true'). Nothing will be filed with "
                + "Qiwa. Set QIWA_USE_LIVE_ADAPTER=true and supply live credentials for real filing.");

        return Task.FromResult<string?>($"sandbox-token-{Guid.NewGuid():N}");
    }

    public Task<QiwaApiResult> PushEmployeeAsync(string accessToken, QiwaEmployeePayload payload, Guid idempotencyKey, CancellationToken ct)
    {
        var missing = MissingFields(payload);
        if (missing.Count > 0)
        {
            _log.LogInformation("Sandbox Qiwa push rejected — missing fields: {Fields}", string.Join(",", missing));
            return Task.FromResult(new QiwaApiResult(
                false, "FIELD_MISSING",
                $"Required field missing: {string.Join(", ", missing)}",
                Envelope("rejected", "\"reason\":\"FIELD_MISSING\"")));
        }

        return Task.FromResult(new QiwaApiResult(true, null, null, Envelope("simulated")));
    }

    public Task<QiwaApiResult> GetEmployeeStatusAsync(string accessToken, string establishmentId, string employeeIdNumber, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(establishmentId) || string.IsNullOrWhiteSpace(employeeIdNumber))
            return Task.FromResult(new QiwaApiResult(false, "FIELD_MISSING", "establishmentId and employeeIdNumber are required.", null));

        return Task.FromResult(new QiwaApiResult(true, null, null, Envelope("simulated", "\"employee_status\":\"unknown\"")));
    }

    /// <summary>
    /// Every sandbox response body, without exception. The status is never the bare
    /// <c>"synced"</c> the real gateway returns, because a stored response payload is
    /// the artefact a customer would point at to prove a filing.
    /// </summary>
    private static string Envelope(string status, string? extra = null) =>
        $"{{\"status\":\"{status}\",{SimulationMarker},\"filed_with_qiwa\":false,\"adapter\":\"sandbox\","
        + $"\"note\":\"Generated by the KynexOne Qiwa sandbox simulator. No request was sent to Qiwa and "
        + $"nothing was filed with MHRSD.\"{(extra is null ? string.Empty : "," + extra)}}}";

    private static List<string> MissingFields(QiwaEmployeePayload p)
    {
        var missing = new List<string>();
        if (string.IsNullOrWhiteSpace(p.EmployeeCode))       missing.Add("employee_code");
        if (string.IsNullOrWhiteSpace(p.IdNumber))           missing.Add("id_number");
        if (string.IsNullOrWhiteSpace(p.IdType))             missing.Add("id_type");
        if (string.IsNullOrWhiteSpace(p.Nationality))        missing.Add("nationality");
        if (string.IsNullOrWhiteSpace(p.SaudiOrNonSaudi))    missing.Add("saudi_or_non_saudi");
        if (string.IsNullOrWhiteSpace(p.OccupationCode))     missing.Add("occupation_code");
        if (string.IsNullOrWhiteSpace(p.EstablishmentId))    missing.Add("establishment_id");
        if (string.IsNullOrWhiteSpace(p.WorkLocationId))     missing.Add("work_location_id");
        if (string.IsNullOrWhiteSpace(p.ContractReference))  missing.Add("contract_reference");
        return missing;
    }
}
