using static Zayra.Api.Tests.Security.LegacyRoleGateBypassSweepTests.Reason;

namespace Zayra.Api.Tests.Security;

/// <summary>
/// The reviewed role-gate bypasses (see <see cref="LegacyRoleGateBypassSweepTests"/>): a seeded role NOT named on
/// an endpoint's <c>[Authorize(Roles)]</c> list that still reaches it through the permission the gate resolves
/// to. One line per endpoint and reason; the reason text is in <see cref="Reasons"/>. Entries marked Open are
/// known gaps carried as follow-ups, not endorsements.
/// </summary>
public sealed partial class LegacyRoleGateBypassSweepTests
{
    internal enum Reason
    {
        SeniorHr,
        TeamScopedRead,
        OrgReadByDesign,
        AggregateOnly,
        PayrollFinanceTier,
        OwnModule,
        BodyRechecksRole,
        FinanceDecisionGuarded,
        WorkflowStepAuthority,
        AttendanceProcessScoped,
        HrOutranksLineManager,
        DisabledStub,
        SameAudienceAsSiblings,
        HrOfficerHrOperations,
        DeviceReadMasked,
        DeviceOpsRead,
        TenantDirectoryRead,
        HrOfficerFilesOnBehalf,
    }

    internal static readonly IReadOnlyDictionary<Reason, string> Reasons = new Dictionary<Reason, string>
    {
        [SeniorHr] = "HR Director is the senior HR tier: its bundle is HR Manager's HR keys plus recruitment, compliance and reports, so it reaches what HR Manager is named on.",
        [TeamScopedRead] = "Read-only for a line Manager/Supervisor: they hold this read key deliberately and DataScope limits any employee rows to their own reporting line.",
        [OrgReadByDesign] = "Read-only, ORG-WIDE: this role holds employees.read (or the module read key) without manager.read, so DataScope is unrestricted and it sees every employee's rows this endpoint returns, within its company scope. Granted by design in AuthSeeder; sensitive fields stay masked without employees.sensitive.",
        [AggregateOnly] = "Returns aggregate counts or totals only, no per-employee rows.",
        [PayrollFinanceTier] = "Payroll/finance role holding this payroll, loan or GL key by design; it already sees the same per-employee pay through the payroll register or loan book.",
        [OwnModule] = "The role's own module: Recruiter holds recruitment.* and Compliance Officer holds compliance.* for exactly this work.",
        [BodyRechecksRole] = "The action body re-checks role names (IsFinanceActor / CanApproveFinance / IsHrLoanActor / the step's approver role / Admin-or-HR-Manager for a tenant-wide approval list; otherwise only the caller's own queue), so the gate bypass reaches only a Forbid or the caller's own items.",
        [FinanceDecisionGuarded] = "Role holds loans.approve by design (Finance Approver approves loans, advances and payroll); the body runs ApprovalDecisionGuard maker-checker and subject separation.",
        [WorkflowStepAuthority] = "ApprovalWorkflowService.CanDecideRequestAsync decides per step (assigned user, employee or role, plus SoD bars). Empty/'Any' step roles are a separate open finding.",
        [AttendanceProcessScoped] = "Data-scoped recompute of daily records from raw punches: a team-scoped Supervisor reaches only their team, a Mobile-mode employee (attendance.write from the access mode) only their own record; a full-range run needs unrestricted scope and locked periods are refused.",
        [HrOutranksLineManager] = "HR Manager outranks the named line Manager on this leave decision and holds leave.approve deliberately.",
        [DisabledStub] = "The action is a stub that always returns 409 (company_status_change_disabled).",
        [SameAudienceAsSiblings] = "Payroll Manager is already named on Create/Update of the same tax policies, and Update can already archive one.",
        [HrOfficerHrOperations] = "HR Officer is HR staff holding this module's write key and the UI exposes these HR screens to it. P2: narrowing tenant HR configuration to the HR-manager tier is a product decision.",
        [DeviceReadMasked] = "Device configuration read only: auth credentials are never serialised and custom header values, secret-looking device parameters and endpoint URL credentials/query are masked for callers without attendance.bulk_import.",
        [DeviceOpsRead] = "NOT data-scoped: every device's sync status and logs in the tenant (device name, vendor, timestamps, event counts, error text). No employee pay, contact or identity data; the endpoint URL's credentials and query are redacted for callers without attendance.bulk_import.",
        [TenantDirectoryRead] = "NOT data-scoped: the whole org chart within the caller's company scope (employee code, name, designation, reporting line). No pay, contact or identity data. A Supervisor sees the tenant's structure, not just their team.",
        [HrOfficerFilesOnBehalf] = "HR Officer files leave and overtime on employees' behalf (leave.write, overtime.write, an owner decision). Raising overtime requests from processed attendance is the same filing, limited by DataScope to the employees the officer can reach, and capped by the overtime policy.",
    };

    internal static readonly (string Endpoint, string Roles, Reason Why)[] AllowList =
    {
        ("POST Absence.ApproveRegularization", "HR Director", SeniorHr),
        ("POST Absence.Record", "HR Officer", HrOfficerHrOperations),
        ("POST Absence.Record", "HR Director", SeniorHr),
        ("POST Absence.RejectRegularization", "HR Director", SeniorHr),
        ("PATCH Advances.Approve", "Payroll Manager,Finance Approver", FinanceDecisionGuarded),
        ("GET Advances.AuditReport", "Payroll Manager,Payroll Officer,Finance Approver", PayrollFinanceTier),
        ("GET Advances.AuditReport", "Manager", TeamScopedRead),
        ("GET Advances.AuditReport", "HR Director", SeniorHr),
        ("PATCH Advances.Reject", "Payroll Manager,Finance Approver", FinanceDecisionGuarded),
        ("POST Applications.AcceptOffer", "Recruiter", OwnModule),
        ("POST Applications.AcceptOffer", "HR Director", SeniorHr),
        ("POST Applications.AddNote", "Recruiter", OwnModule),
        ("POST Applications.AddNote", "HR Director", SeniorHr),
        ("POST Applications.Advance", "Recruiter", OwnModule),
        ("POST Applications.Advance", "HR Director", SeniorHr),
        ("POST Applications.Apply", "Recruiter", OwnModule),
        ("POST Applications.Apply", "HR Director", SeniorHr),
        ("POST Applications.DeclineOffer", "Recruiter", OwnModule),
        ("POST Applications.DeclineOffer", "HR Director", SeniorHr),
        ("POST Applications.GenerateOffer", "Recruiter", OwnModule),
        ("POST Applications.GenerateOffer", "HR Director", SeniorHr),
        ("GET Applications.Get", "HR Director", SeniorHr),
        ("GET Applications.GetOfferHtml", "HR Director", SeniorHr),
        ("GET Applications.Kanban", "HR Director", SeniorHr),
        ("GET Applications.List", "HR Director", SeniorHr),
        ("POST Applications.RecordFeedback", "Recruiter", OwnModule),
        ("POST Applications.RecordFeedback", "HR Director", SeniorHr),
        ("POST Applications.Reject", "HR Director", SeniorHr),
        ("POST Applications.ScheduleInterview", "Recruiter", OwnModule),
        ("POST Applications.ScheduleInterview", "HR Director", SeniorHr),
        ("POST Applications.SendOffer", "Recruiter", OwnModule),
        ("POST Applications.SendOffer", "HR Director", SeniorHr),
        ("POST ApprovalWorkflows.Decide", "HR Director", SeniorHr),
        ("POST ApprovalWorkflows.Decide", "Payroll Manager,Finance,Finance Approver,Employee+ManagerPortal", WorkflowStepAuthority),
        ("GET ApprovalWorkflows.Get", "Payroll Manager,HR Officer,Payroll Officer,Finance,Finance Approver,Compliance Officer", OrgReadByDesign),
        ("GET ApprovalWorkflows.Get", "Manager,Employee+ManagerPortal", TeamScopedRead),
        ("GET ApprovalWorkflows.Get", "HR Director", SeniorHr),
        ("GET ApprovalWorkflows.List", "Payroll Manager,HR Officer,Payroll Officer,Finance,Finance Approver,Compliance Officer", OrgReadByDesign),
        ("GET ApprovalWorkflows.List", "Manager,Employee+ManagerPortal", TeamScopedRead),
        ("GET ApprovalWorkflows.Requests", "Employee+ManagerPortal", BodyRechecksRole),
        ("GET ApprovalWorkflows.List", "HR Director", SeniorHr),
        ("GET ApprovalWorkflows.Requests", "Payroll Manager,Payroll Officer,Finance,Finance Approver,Compliance Officer", OrgReadByDesign),
        ("GET ApprovalWorkflows.Requests", "HR Director", SeniorHr),
        ("POST Assessments.CreateTemplate", "Recruiter", OwnModule),
        ("POST Assessments.CreateTemplate", "HR Director", SeniorHr),
        ("GET Assessments.List", "HR Director", SeniorHr),
        ("PATCH Assessments.RecordResult", "HR Director", SeniorHr),
        ("POST Assessments.Send", "HR Director", SeniorHr),
        ("POST Attendance.CreateDevice", "HR Director", SeniorHr),
        ("GET Attendance.Dashboard", "Payroll Manager,Payroll Officer,HR Assistant", OrgReadByDesign),
        ("DELETE Attendance.DeleteDevice", "HR Director", SeniorHr),
        ("GET Attendance.Device", "Payroll Manager,Payroll Officer,Manager,Supervisor,HR Assistant", DeviceReadMasked),
        ("GET Attendance.Device", "HR Director", SeniorHr),
        ("GET Attendance.Devices", "Payroll Manager,Payroll Officer,Manager,Supervisor,HR Assistant", DeviceReadMasked),
        ("GET Attendance.Devices", "HR Director", SeniorHr),
        ("POST Attendance.GenerateDeviceKey", "HR Director", SeniorHr),
        ("POST Attendance.Import", "HR Director", SeniorHr),
        ("GET Attendance.Insights", "Payroll Manager,HR Officer,Payroll Officer,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Attendance.Insights", "Manager,Supervisor", TeamScopedRead),
        ("GET Attendance.PendingRegularization", "Payroll Manager,HR Officer,Payroll Officer,HR Assistant,Auditor", OrgReadByDesign),
        ("POST Attendance.Process", "Supervisor", AttendanceProcessScoped),
        ("POST Attendance.ProcessInBackground", "Supervisor", AttendanceProcessScoped),
        ("GET Attendance.ReportDeviceSync", "Payroll Manager,Payroll Officer,HR Assistant", OrgReadByDesign),
        ("GET Attendance.ReportDeviceSync", "Manager,Supervisor", DeviceOpsRead),
        ("POST Attendance.Reprocess", "Supervisor", AttendanceProcessScoped),
        ("POST Attendance.Sync", "HR Director", SeniorHr),
        ("GET Attendance.SyncLogs", "Payroll Manager,Payroll Officer,HR Assistant", OrgReadByDesign),
        ("GET Attendance.SyncLogs", "Manager,Supervisor", DeviceOpsRead),
        ("GET Attendance.SyncLogs", "HR Director", SeniorHr),
        ("POST Attendance.TestConnection", "HR Director", SeniorHr),
        ("GET Attendance.Today", "Payroll Manager,Payroll Officer,HR Assistant", OrgReadByDesign),
        ("PUT Attendance.UpdateDevice", "HR Director", SeniorHr),
        ("GET AuditLogs.Integrity", "HR Manager,Compliance Officer,Auditor", OrgReadByDesign),
        ("GET AuditLogs.Integrity", "HR Director", SeniorHr),
        ("GET AuditLogs.Recent", "HR Manager,Compliance Officer,Auditor", OrgReadByDesign),
        ("GET AuditLogs.Recent", "HR Director", SeniorHr),
        ("GET BankConfirmations.History", "Finance Approver", PayrollFinanceTier),
        ("GET BankConfirmations.History", "HR Director", SeniorHr),
        ("POST Benefits.AddContribution", "HR Director", SeniorHr),
        ("POST Benefits.AddEligibility", "HR Director", SeniorHr),
        ("GET Benefits.CheckEligibility", "Payroll Manager,Payroll Officer,Finance Approver", PayrollFinanceTier),
        ("GET Benefits.CheckEligibility", "HR Director", SeniorHr),
        ("POST Benefits.CreatePlan", "HR Director", SeniorHr),
        ("DELETE Benefits.DeactivateEligibility", "HR Director", SeniorHr),
        ("POST Benefits.Enroll", "HR Director", SeniorHr),
        ("GET Benefits.GetEnrollment", "Payroll Manager,Payroll Officer,Finance Approver", PayrollFinanceTier),
        ("GET Benefits.GetEnrollment", "HR Director", SeniorHr),
        ("POST Benefits.LinkPayrollDeduction", "HR Director", SeniorHr),
        ("GET Benefits.ListDeductionCandidates", "Payroll Manager,Payroll Officer,Finance Approver", PayrollFinanceTier),
        ("GET Benefits.ListDeductionCandidates", "HR Director", SeniorHr),
        ("GET Benefits.ListEligibility", "Payroll Manager,Payroll Officer,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Benefits.ListEligibility", "Manager,Supervisor", TeamScopedRead),
        ("GET Benefits.ListEligibility", "HR Director", SeniorHr),
        ("GET Benefits.ListEnrollments", "Payroll Manager,Payroll Officer,Finance Approver", PayrollFinanceTier),
        ("GET Benefits.ListEnrollments", "HR Director", SeniorHr),
        ("GET Benefits.ListPlans", "Payroll Manager,Payroll Officer,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Benefits.ListPlans", "Manager,Supervisor", TeamScopedRead),
        ("GET Benefits.ListPlans", "HR Director", SeniorHr),
        ("PUT Benefits.UpdatePlan", "HR Director", SeniorHr),
        ("GET Bonuses.AuditReport", "Payroll Manager,Payroll Officer,Finance Approver,Auditor", AggregateOnly),
        ("GET Bonuses.AuditReport", "HR Director", SeniorHr),
        ("GET Bonuses.GetPayrollPendingBonuses", "Payroll Manager,Payroll Officer,Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Bonuses.GetPayrollPendingBonuses", "HR Director", SeniorHr),
        ("POST Branches.Create", "HR Director", SeniorHr),
        ("DELETE Branches.Delete", "HR Director", SeniorHr),
        ("GET Branches.Export", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Branches.Export", "HR Director", SeniorHr),
        ("GET Branches.Get", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Branches.Get", "HR Director", SeniorHr),
        ("POST Branches.Import", "HR Director", SeniorHr),
        ("POST Branches.ImportPreview", "HR Director", SeniorHr),
        ("GET Branches.ImportTemplate", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Branches.ImportTemplate", "HR Director", SeniorHr),
        ("GET Branches.Search", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Branches.Search", "HR Director", SeniorHr),
        ("PUT Branches.Update", "HR Director", SeniorHr),
        ("POST Calibration.AdjustScore", "HR Director", SeniorHr),
        ("GET Calibration.GetBoard", "HR Director", SeniorHr),
        ("POST Candidates.Blacklist", "Recruiter", OwnModule),
        ("POST Candidates.Blacklist", "HR Director", SeniorHr),
        ("POST Candidates.Create", "Recruiter", OwnModule),
        ("POST Candidates.Create", "HR Director", SeniorHr),
        ("GET Candidates.Get", "HR Director", SeniorHr),
        ("GET Candidates.List", "HR Director", SeniorHr),
        ("PUT Candidates.Update", "Recruiter", OwnModule),
        ("PUT Candidates.Update", "HR Director", SeniorHr),
        ("POST CompOff.Approve", "HR Manager", HrOutranksLineManager),
        ("POST CompOff.Approve", "HR Director", SeniorHr),
        ("POST CompOff.Create", "HR Officer", HrOfficerHrOperations),
        ("POST CompOff.Create", "HR Director", SeniorHr),
        ("POST Companies.Create", "HR Director", SeniorHr),
        ("DELETE Companies.Delete", "HR Director", SeniorHr),
        ("GET Companies.Export", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Companies.Export", "HR Director", SeniorHr),
        ("GET Companies.Get", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Companies.Get", "HR Director", SeniorHr),
        ("POST Companies.Import", "HR Director", SeniorHr),
        ("POST Companies.ImportPreview", "HR Director", SeniorHr),
        ("GET Companies.ImportTemplate", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Companies.ImportTemplate", "HR Director", SeniorHr),
        ("GET Companies.Search", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Companies.Search", "HR Director", SeniorHr),
        ("PUT Companies.SetStatus", "HR Manager", DisabledStub),
        ("PUT Companies.SetStatus", "HR Director", SeniorHr),
        ("PUT Companies.Update", "HR Director", SeniorHr),
        ("POST CompanyComplianceProfiles.Create", "HR Director", SeniorHr),
        ("PUT CompanyComplianceProfiles.Update", "HR Director", SeniorHr),
        ("PATCH CompanyComplianceProfiles.UpdateJawazatPolicy", "HR Director", SeniorHr),
        ("DELETE CompanyTaxPolicies.Delete", "Payroll Manager", SameAudienceAsSiblings),
        ("POST Competencies.Create", "HR Director", SeniorHr),
        ("DELETE Competencies.Delete", "HR Director", SeniorHr),
        ("PUT Competencies.Update", "HR Director", SeniorHr),
        ("GET ComplianceReports.AIInsights", "Compliance Officer", OwnModule),
        ("GET ComplianceReports.AIInsights", "Auditor", OrgReadByDesign),
        ("GET ComplianceReports.AIInsights", "HR Director", SeniorHr),
        ("POST ComplianceReports.CreateDocType", "Compliance Officer", OwnModule),
        ("POST ComplianceReports.CreateDocType", "HR Director", SeniorHr),
        ("GET ComplianceReports.EmployeeIdentityIntegrity", "Compliance Officer", OwnModule),
        ("GET ComplianceReports.EmployeeIdentityIntegrity", "Auditor", OrgReadByDesign),
        ("GET ComplianceReports.EmployeeIdentityIntegrity", "HR Director", SeniorHr),
        ("POST Contracts.Create", "Compliance Officer", OwnModule),
        ("POST Contracts.Create", "HR Director", SeniorHr),
        ("POST Contracts.CreateTemplate", "Compliance Officer", OwnModule),
        ("POST Contracts.CreateTemplate", "HR Director", SeniorHr),
        ("GET Contracts.Get", "Compliance Officer", OwnModule),
        ("GET Contracts.Get", "Auditor", OrgReadByDesign),
        ("GET Contracts.Get", "HR Director", SeniorHr),
        ("GET Contracts.GetTemplate", "Compliance Officer", OwnModule),
        ("GET Contracts.GetTemplate", "Auditor", OrgReadByDesign),
        ("GET Contracts.GetTemplate", "HR Director", SeniorHr),
        ("GET Contracts.List", "Compliance Officer", OwnModule),
        ("GET Contracts.List", "Auditor", OrgReadByDesign),
        ("GET Contracts.List", "HR Director", SeniorHr),
        ("GET Contracts.ListTemplates", "Compliance Officer", OwnModule),
        ("GET Contracts.ListTemplates", "Auditor", OrgReadByDesign),
        ("GET Contracts.ListTemplates", "HR Director", SeniorHr),
        ("POST Contracts.Supersede", "Compliance Officer", OwnModule),
        ("POST Contracts.Supersede", "HR Director", SeniorHr),
        ("PATCH Contracts.UpdateStatus", "Compliance Officer", OwnModule),
        ("PATCH Contracts.UpdateStatus", "HR Director", SeniorHr),
        ("POST CostCenters.Create", "HR Director", SeniorHr),
        ("DELETE CostCenters.Delete", "HR Director", SeniorHr),
        ("GET CostCenters.Export", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET CostCenters.Export", "HR Director", SeniorHr),
        ("GET CostCenters.Get", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET CostCenters.Get", "HR Director", SeniorHr),
        ("POST CostCenters.Import", "HR Director", SeniorHr),
        ("POST CostCenters.ImportPreview", "HR Director", SeniorHr),
        ("GET CostCenters.ImportTemplate", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET CostCenters.ImportTemplate", "HR Director", SeniorHr),
        ("GET CostCenters.Search", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET CostCenters.Search", "HR Director", SeniorHr),
        ("PUT CostCenters.Update", "HR Director", SeniorHr),
        ("GET CountryPack.GetAvailable", "HR Assistant", OrgReadByDesign),
        ("GET CountryPack.GetAvailable", "HR Director", SeniorHr),
        ("GET CountryPack.GetStatutorySummary", "HR Officer,HR Assistant", OrgReadByDesign),
        ("GET CountryPack.GetStatutorySummary", "HR Director", SeniorHr),
        ("POST Cycles.Advance", "HR Director", SeniorHr),
        ("POST Cycles.Close", "HR Director", SeniorHr),
        ("POST Cycles.Create", "HR Director", SeniorHr),
        ("POST Cycles.Launch", "HR Director", SeniorHr),
        ("PUT Cycles.Update", "HR Director", SeniorHr),
        ("POST Departments.Create", "HR Director", SeniorHr),
        ("DELETE Departments.Delete", "HR Director", SeniorHr),
        ("GET Departments.Export", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Departments.Export", "HR Director", SeniorHr),
        ("GET Departments.Get", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Departments.Get", "HR Director", SeniorHr),
        ("POST Departments.Import", "HR Director", SeniorHr),
        ("POST Departments.ImportPreview", "HR Director", SeniorHr),
        ("GET Departments.ImportTemplate", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Departments.ImportTemplate", "HR Director", SeniorHr),
        ("GET Departments.Search", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Departments.Search", "HR Director", SeniorHr),
        ("PUT Departments.Update", "HR Director", SeniorHr),
        ("POST Designations.Create", "HR Director", SeniorHr),
        ("DELETE Designations.Delete", "HR Director", SeniorHr),
        ("GET Designations.Export", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Designations.Export", "HR Director", SeniorHr),
        ("GET Designations.Get", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Designations.Get", "HR Director", SeniorHr),
        ("POST Designations.Import", "HR Director", SeniorHr),
        ("POST Designations.ImportPreview", "HR Director", SeniorHr),
        ("GET Designations.ImportTemplate", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Designations.ImportTemplate", "HR Director", SeniorHr),
        ("GET Designations.Search", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Designations.Search", "HR Director", SeniorHr),
        ("PUT Designations.Update", "HR Director", SeniorHr),
        ("POST EmployeeSelfService.ApproveProfileChange", "HR Director", SeniorHr),
        ("GET EmployeeSelfService.ProfileChangeRequests", "HR Director", SeniorHr),
        ("POST EmployeeSelfService.RejectProfileChange", "HR Director", SeniorHr),
        ("GET Employees.AiInsights", "Payroll Manager,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Employees.AiInsights", "Supervisor", TeamScopedRead),
        ("GET Employees.AiInsights", "HR Director", SeniorHr),
        ("GET Employees.AppointmentLetter", "HR Director", SeniorHr),
        ("POST Employees.CheckDocumentExpiry", "HR Officer", HrOfficerHrOperations),
        ("POST Employees.CheckDocumentExpiry", "HR Director", SeniorHr),
        ("GET Employees.ExEmployees", "Payroll Manager,Payroll Officer,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Employees.ExEmployees", "Manager,Supervisor", TeamScopedRead),
        ("GET Employees.ExEmployees", "HR Director", SeniorHr),
        ("GET Employees.ExperienceLetter", "HR Director", SeniorHr),
        ("GET Employees.ExpiringDocuments", "Payroll Manager,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Employees.ExpiringDocuments", "Manager,Supervisor", TeamScopedRead),
        ("GET Employees.ExpiringDocuments", "HR Director", SeniorHr),
        ("GET Employees.Export", "HR Director", SeniorHr),
        ("GET Employees.FieldCatalog", "Payroll Manager,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Employees.FieldCatalog", "Manager,Supervisor", TeamScopedRead),
        ("GET Employees.FieldCatalog", "HR Director", SeniorHr),
        ("GET Employees.GetReportingLines", "Payroll Manager,Payroll Officer,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Employees.GetReportingLines", "Manager,Supervisor", TeamScopedRead),
        ("GET Employees.GetReportingLines", "HR Director", SeniorHr),
        ("GET Employees.Headcount", "Payroll Manager,Finance,Finance Approver,Compliance Officer,Manager,Supervisor,Recruiter,HR Assistant", AggregateOnly),
        ("GET Employees.Headcount", "HR Director", SeniorHr),
        ("GET Employees.ImportTemplate", "Payroll Manager,Payroll Officer,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Employees.ImportTemplate", "Manager,Supervisor", TeamScopedRead),
        ("GET Employees.ImportTemplate", "HR Director", SeniorHr),
        ("GET Employees.MissingDocuments", "Payroll Manager,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Employees.MissingDocuments", "Manager,Supervisor", TeamScopedRead),
        ("GET Employees.MissingDocuments", "HR Director", SeniorHr),
        ("GET Employees.OrgChart", "Payroll Manager,Payroll Officer,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Employees.OrgChart", "Supervisor", TenantDirectoryRead),
        ("GET Employees.OrgChart", "HR Director", SeniorHr),
        ("GET Employees.Readiness", "Payroll Manager,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Employees.Readiness", "Supervisor", TeamScopedRead),
        ("GET Employees.Readiness", "HR Director", SeniorHr),
        ("GET Employees.Reports", "Payroll Manager,Finance,Finance Approver,Compliance Officer,Manager,Supervisor,Recruiter,HR Assistant", AggregateOnly),
        ("GET Employees.Reports", "HR Director", SeniorHr),
        ("GET Employees.ResolveHierarchy", "Payroll Manager,Payroll Officer,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Employees.ResolveHierarchy", "Supervisor", TeamScopedRead),
        ("GET Employees.ResolveHierarchy", "HR Director", SeniorHr),
        ("GET Employees.ResolveWorkflowApprovers", "Finance,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Employees.ResolveWorkflowApprovers", "Supervisor", TeamScopedRead),
        ("GET Employees.ResolveWorkflowApprovers", "HR Director", SeniorHr),
        ("GET Employees.Search", "Payroll Manager,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Employees.Search", "Supervisor", TeamScopedRead),
        ("GET Employees.Search", "HR Director", SeniorHr),
        ("GET Employees.StatusSummary", "Payroll Manager,Finance,Finance Approver,Compliance Officer,Manager,Supervisor,Recruiter,HR Assistant", AggregateOnly),
        ("GET Employees.StatusSummary", "HR Director", SeniorHr),
        ("PUT Employees.UpdateEmployee", "HR Director", SeniorHr),
        ("POST Encashment.HRApprove", "HR Director", SeniorHr),
        ("POST Encashment.PayrollApprove", "HR Manager,Finance Approver", PayrollFinanceTier),
        ("POST Encashment.Reject", "HR Director", SeniorHr),
        ("POST Encashment.Void", "HR Manager,Finance Approver", PayrollFinanceTier),
        ("POST Goals.Approve", "HR Director", SeniorHr),
        ("POST Goals.Create", "HR Director", SeniorHr),
        ("DELETE Goals.Delete", "HR Director", SeniorHr),
        ("PUT Goals.Update", "HR Director", SeniorHr),
        ("GET Gosi.GetContributionRules", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Gosi.GetContributionRules", "HR Director", SeniorHr),
        ("GET Gosi.GetEmployeeReadiness", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Gosi.GetEmployeeReadiness", "HR Director", SeniorHr),
        ("GET Gosi.GetPeriodContributionSummary", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Gosi.GetPeriodContributionSummary", "HR Director", SeniorHr),
        ("GET Gosi.GetReadinessSummary", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Gosi.GetReadinessSummary", "HR Director", SeniorHr),
        ("GET Gosi.GetRunContributionSummary", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Gosi.GetRunContributionSummary", "HR Director", SeniorHr),
        ("GET Gosi.GetVarianceReport", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Gosi.GetVarianceReport", "HR Director", SeniorHr),
        ("POST Grades.Create", "HR Director", SeniorHr),
        ("DELETE Grades.Delete", "HR Director", SeniorHr),
        ("GET Grades.Export", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Grades.Export", "HR Director", SeniorHr),
        ("GET Grades.Get", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Grades.Get", "HR Director", SeniorHr),
        ("GET Grades.GetPayScale", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Grades.GetPayScale", "HR Director", SeniorHr),
        ("POST Grades.Import", "HR Director", SeniorHr),
        ("POST Grades.ImportPreview", "HR Director", SeniorHr),
        ("GET Grades.ImportTemplate", "Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Grades.ImportTemplate", "HR Director", SeniorHr),
        ("GET Grades.Search", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Grades.Search", "HR Director", SeniorHr),
        ("PUT Grades.SetPayScale", "HR Director", SeniorHr),
        ("PUT Grades.Update", "HR Director", SeniorHr),
        ("GET GroupDashboard.Get", "Payroll Manager,HR Officer,Payroll Officer,Finance,Manager,Supervisor,Recruiter,HR Assistant,Employee", AggregateOnly),
        ("POST HRRequestCenter.AddComment", "HR Director", SeniorHr),
        ("POST HRRequestCenter.CreateCategory", "HR Officer", HrOfficerHrOperations),
        ("POST HRRequestCenter.CreateCategory", "HR Director", SeniorHr),
        ("POST HRRequestCenter.CreateSla", "HR Officer", HrOfficerHrOperations),
        ("POST HRRequestCenter.CreateSla", "HR Director", SeniorHr),
        ("GET HRRequestCenter.Dashboard", "HR Director", SeniorHr),
        ("GET HRRequestCenter.ListSlas", "Payroll Manager,HR Officer,Payroll Officer,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET HRRequestCenter.ListSlas", "Manager,Supervisor", TeamScopedRead),
        ("GET HRRequestCenter.ListSlas", "HR Director", SeniorHr),
        ("PATCH HRRequestCenter.UpdateStatus", "HR Director", SeniorHr),
        ("POST HolidayCalendar.AddHoliday", "HR Officer", HrOfficerHrOperations),
        ("POST HolidayCalendar.AddHoliday", "HR Director", SeniorHr),
        ("POST HolidayCalendar.CreateBlackout", "HR Officer", HrOfficerHrOperations),
        ("POST HolidayCalendar.CreateBlackout", "HR Director", SeniorHr),
        ("POST HolidayCalendar.CreateCalendar", "HR Officer", HrOfficerHrOperations),
        ("POST HolidayCalendar.CreateCalendar", "HR Director", SeniorHr),
        ("DELETE HolidayCalendar.DeleteCalendar", "HR Director", SeniorHr),
        ("DELETE HolidayCalendar.DeleteHoliday", "HR Director", SeniorHr),
        ("PUT HolidayCalendar.UpdateCalendar", "HR Officer", HrOfficerHrOperations),
        ("PUT HolidayCalendar.UpdateCalendar", "HR Director", SeniorHr),
        ("PUT HolidayCalendar.UpdateHoliday", "HR Officer", HrOfficerHrOperations),
        ("PUT HolidayCalendar.UpdateHoliday", "HR Director", SeniorHr),
        ("POST HrLetters.DeclineRequest", "HR Director", SeniorHr),
        ("POST HrLetters.Issue", "HR Director", SeniorHr),
        ("POST HrLetters.IssueForRequest", "HR Director", SeniorHr),
        ("GET HrLetters.Register", "Payroll Manager,Payroll Officer,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET HrLetters.Register", "Manager,Supervisor", TeamScopedRead),
        ("GET HrLetters.Register", "HR Director", SeniorHr),
        ("GET HrLetters.Reprint", "HR Director", SeniorHr),
        ("GET HrLetters.Requests", "Payroll Manager,Payroll Officer,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET HrLetters.Requests", "Manager,Supervisor", TeamScopedRead),
        ("GET HrLetters.Requests", "HR Director", SeniorHr),
        ("POST HrLetters.SeedDefaults", "HR Officer", HrOfficerHrOperations),
        ("POST HrLetters.SeedDefaults", "HR Director", SeniorHr),
        ("GET HrLetters.Templates", "Payroll Manager,HR Officer,Payroll Officer,Finance,Finance Approver,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET HrLetters.Templates", "Manager,Supervisor", TeamScopedRead),
        ("GET HrLetters.Templates", "HR Director", SeniorHr),
        ("PUT HrLetters.UpdateTemplate", "HR Officer", HrOfficerHrOperations),
        ("PUT HrLetters.UpdateTemplate", "HR Director", SeniorHr),
        ("PATCH Interviews.Cancel", "HR Director", SeniorHr),
        ("PATCH Interviews.Complete", "HR Director", SeniorHr),
        ("GET Interviews.Get", "HR Director", SeniorHr),
        ("GET Interviews.GetFeedback", "HR Director", SeniorHr),
        ("GET Interviews.List", "HR Director", SeniorHr),
        ("POST Interviews.Schedule", "HR Director", SeniorHr),
        ("POST Interviews.SubmitFeedback", "HR Director", SeniorHr),
        ("POST Leave.Approve", "HR Director", SeniorHr),
        ("POST Leave.Reject", "HR Director", SeniorHr),
        ("POST LeaveAIInsights.Generate", "HR Officer", HrOfficerHrOperations),
        ("POST LeaveAIInsights.Generate", "HR Director", SeniorHr),
        ("POST LeaveBalances.Adjust", "HR Officer", HrOfficerHrOperations),
        ("POST LeaveBalances.Adjust", "HR Director", SeniorHr),
        ("POST LeaveBalances.TriggerAccrual", "HR Officer", HrOfficerHrOperations),
        ("POST LeaveBalances.TriggerAccrual", "HR Director", SeniorHr),
        ("DELETE LeavePolicies.Archive", "HR Officer", HrOfficerHrOperations),
        ("DELETE LeavePolicies.Archive", "HR Director", SeniorHr),
        ("POST LeavePolicies.Create", "HR Officer", HrOfficerHrOperations),
        ("POST LeavePolicies.Create", "HR Director", SeniorHr),
        ("PUT LeavePolicies.Update", "HR Officer", HrOfficerHrOperations),
        ("PUT LeavePolicies.Update", "HR Director", SeniorHr),
        ("GET LeaveReports.Liability", "HR Director", SeniorHr),
        ("POST LeaveRequests.Approve", "HR Director", SeniorHr),
        ("POST LeaveRequests.ApproveCancellation", "HR Director", SeniorHr),
        ("GET LeaveRequests.Export", "Payroll Manager,HR Assistant", OrgReadByDesign),
        ("GET LeaveRequests.Export", "Manager,Supervisor", TeamScopedRead),
        ("GET LeaveRequests.Export", "HR Director", SeniorHr),
        ("POST LeaveRequests.Import", "HR Director", SeniorHr),
        ("GET LeaveRequests.ImportTemplate", "Payroll Manager,HR Assistant,Auditor", OrgReadByDesign),
        ("GET LeaveRequests.ImportTemplate", "Manager,Supervisor", TeamScopedRead),
        ("GET LeaveRequests.ImportTemplate", "HR Director", SeniorHr),
        ("POST LeaveRequests.Reject", "HR Director", SeniorHr),
        ("POST LeaveRequests.RejectCancellation", "HR Director", SeniorHr),
        ("POST LeaveTypes.Create", "HR Officer", HrOfficerHrOperations),
        ("POST LeaveTypes.Create", "HR Director", SeniorHr),
        ("DELETE LeaveTypes.Delete", "HR Director", SeniorHr),
        ("GET LeaveTypes.Export", "Payroll Manager,HR Assistant", OrgReadByDesign),
        ("GET LeaveTypes.Export", "Manager,Supervisor", TeamScopedRead),
        ("GET LeaveTypes.Export", "HR Director", SeniorHr),
        ("POST LeaveTypes.Import", "HR Officer", HrOfficerHrOperations),
        ("POST LeaveTypes.Import", "HR Director", SeniorHr),
        ("GET LeaveTypes.ImportTemplate", "Payroll Manager,HR Assistant,Auditor", OrgReadByDesign),
        ("GET LeaveTypes.ImportTemplate", "Manager,Supervisor", TeamScopedRead),
        ("GET LeaveTypes.ImportTemplate", "HR Director", SeniorHr),
        ("PUT LeaveTypes.Update", "HR Officer", HrOfficerHrOperations),
        ("PUT LeaveTypes.Update", "HR Director", SeniorHr),
        ("POST Loans.AddApprovalStep", "Finance", BodyRechecksRole),
        ("PATCH Loans.ApprovePaymentBatch", "HR Manager,Payroll Manager", BodyRechecksRole),
        ("GET Loans.AuditReport", "Payroll Manager,Payroll Officer,Finance Approver", PayrollFinanceTier),
        ("GET Loans.AuditReport", "Manager", TeamScopedRead),
        ("GET Loans.AuditReport", "HR Director", SeniorHr),
        ("PATCH Loans.CancelPaymentBatch", "HR Manager", BodyRechecksRole),
        ("PATCH Loans.ConfirmPaymentBatchPaid", "HR Manager", BodyRechecksRole),
        ("POST Loans.CreatePaymentBatch", "HR Manager", BodyRechecksRole),
        ("PATCH Loans.DecideApproval", "Payroll Manager,Finance,Finance Approver", BodyRechecksRole),
        ("PATCH Loans.DecideLoanChange", "HR Manager,Payroll Manager,Finance Approver", BodyRechecksRole),
        ("PATCH Loans.DecideLoanCorrection", "HR Manager,Payroll Manager,Finance Approver", BodyRechecksRole),
        ("GET Loans.ExportPaymentBatch", "HR Manager,Payroll Manager,Payroll Officer,Manager", BodyRechecksRole),
        ("GET Loans.ExportPaymentBatch", "HR Director", SeniorHr),
        ("GET Loans.GetPaymentBatch", "HR Manager,Payroll Manager,Payroll Officer,Manager", BodyRechecksRole),
        ("GET Loans.GetPaymentBatch", "HR Director", SeniorHr),
        ("GET Loans.ListLoanCorrections", "HR Manager,Payroll Manager,Payroll Officer,Finance Approver,Manager", BodyRechecksRole),
        ("GET Loans.ListLoanCorrections", "HR Director", SeniorHr),
        ("GET Loans.ListPaymentBatches", "HR Manager,Payroll Manager,Payroll Officer,Manager", BodyRechecksRole),
        ("GET Loans.ListPaymentBatches", "HR Director", SeniorHr),
        ("PATCH Loans.RecordPaymentLineOutcome", "HR Manager", BodyRechecksRole),
        ("POST Loans.RecordRepayment", "HR Manager", BodyRechecksRole),
        ("POST Loans.RequestLoanCorrection", "HR Manager", BodyRechecksRole),
        ("POST Loans.RefreshLoanLifecycle", "Payroll Manager", BodyRechecksRole),
        ("POST Locations.Create", "HR Director", SeniorHr),
        ("DELETE Locations.Delete", "HR Director", SeniorHr),
        ("GET Locations.Export", "HR Officer,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Locations.Export", "HR Director", SeniorHr),
        ("GET Locations.Get", "HR Officer,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Locations.Get", "HR Director", SeniorHr),
        ("POST Locations.Import", "HR Director", SeniorHr),
        ("POST Locations.ImportPreview", "HR Director", SeniorHr),
        ("GET Locations.ImportTemplate", "HR Officer,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Locations.ImportTemplate", "HR Director", SeniorHr),
        ("GET Locations.Search", "HR Officer,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET Locations.Search", "HR Director", SeniorHr),
        ("PUT Locations.Update", "HR Director", SeniorHr),
        ("POST MigrationImport.Commit", "HR Officer", HrOfficerHrOperations),
        ("POST MigrationImport.Commit", "HR Director", SeniorHr),
        ("GET MigrationImport.Get", "HR Officer", OrgReadByDesign),
        ("GET MigrationImport.Get", "HR Director", SeniorHr),
        ("POST MigrationImport.Preview", "HR Officer", HrOfficerHrOperations),
        ("POST MigrationImport.Preview", "HR Director", SeniorHr),
        ("POST MigrationImport.Resume", "HR Officer", HrOfficerHrOperations),
        ("POST MigrationImport.Resume", "HR Director", SeniorHr),
        ("GET MigrationImport.Template", "HR Officer", OrgReadByDesign),
        ("GET MigrationImport.Template", "HR Director", SeniorHr),
        ("GET Offboarding.Get", "Payroll Manager,Finance Approver", PayrollFinanceTier),
        ("GET Offboarding.Get", "HR Director", SeniorHr),
        ("GET Offboarding.List", "Payroll Manager,Finance Approver", PayrollFinanceTier),
        ("GET Offboarding.List", "HR Director", SeniorHr),
        ("GET Offboarding.Summary", "Payroll Manager,Finance Approver", PayrollFinanceTier),
        ("GET Offboarding.Summary", "HR Director", SeniorHr),
        ("PATCH Offers.Accept", "Recruiter", OwnModule),
        ("PATCH Offers.Accept", "HR Director", SeniorHr),
        ("POST Offers.AddApproval", "Recruiter", OwnModule),
        ("POST Offers.AddApproval", "HR Director", SeniorHr),
        ("GET Offers.ApproverOptions", "Recruiter", OwnModule),
        ("GET Offers.ApproverOptions", "HR Director", SeniorHr),
        ("POST Offers.Create", "HR Director", SeniorHr),
        ("PATCH Offers.DecideApproval", "HR Director", SeniorHr),
        ("PATCH Offers.Decline", "Recruiter", OwnModule),
        ("PATCH Offers.Decline", "HR Director", SeniorHr),
        ("GET Offers.Download", "HR Director", SeniorHr),
        ("GET Offers.Get", "HR Director", SeniorHr),
        ("GET Offers.List", "HR Director", SeniorHr),
        ("GET Offers.PlacementOptions", "HR Director", SeniorHr),
        ("PATCH Offers.Send", "Recruiter", OwnModule),
        ("PATCH Offers.Send", "HR Director", SeniorHr),
        ("POST Onboarding.CreateBulkFromChecklist", "HR Director", SeniorHr),
        ("POST Onboarding.CreateChecklist", "Recruiter", OwnModule),
        ("POST Onboarding.CreateChecklist", "HR Director", SeniorHr),
        ("POST Onboarding.CreateTask", "HR Director", SeniorHr),
        ("GET Onboarding.ListChecklists", "HR Director", SeniorHr),
        ("GET Onboarding.ListTasks", "HR Director", SeniorHr),
        ("GET Onboarding.ListTemplateTasks", "HR Director", SeniorHr),
        ("GET Onboarding.Summary", "HR Director", SeniorHr),
        ("PATCH Onboarding.UpdateTaskStatus", "HR Director", SeniorHr),
        ("POST Onboarding.UpsertTemplateTask", "Recruiter", OwnModule),
        ("POST Onboarding.UpsertTemplateTask", "HR Director", SeniorHr),
        ("POST Openings.Close", "Recruiter", OwnModule),
        ("POST Openings.Close", "HR Director", SeniorHr),
        ("POST Openings.Create", "Recruiter", OwnModule),
        ("POST Openings.Create", "HR Director", SeniorHr),
        ("POST Openings.Import", "Recruiter", OwnModule),
        ("POST Openings.Import", "HR Director", SeniorHr),
        ("PUT Openings.Update", "Recruiter", OwnModule),
        ("PUT Openings.Update", "HR Director", SeniorHr),
        ("GET Organization.Branches", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Organization.Branches", "HR Director", SeniorHr),
        ("GET Organization.Companies", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Organization.Companies", "HR Director", SeniorHr),
        ("GET Organization.Company", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Organization.Company", "HR Director", SeniorHr),
        ("GET Organization.CostCenters", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Organization.CostCenters", "HR Director", SeniorHr),
        ("POST Organization.CreateBranch", "HR Director", SeniorHr),
        ("POST Organization.CreateCompany", "HR Director", SeniorHr),
        ("POST Organization.CreateCostCenter", "HR Director", SeniorHr),
        ("POST Organization.CreateDepartment", "HR Director", SeniorHr),
        ("POST Organization.CreateDesignation", "HR Director", SeniorHr),
        ("POST Organization.CreateGrade", "HR Director", SeniorHr),
        ("GET Organization.Departments", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Organization.Departments", "HR Director", SeniorHr),
        ("GET Organization.Designations", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Organization.Designations", "HR Director", SeniorHr),
        ("GET Organization.Grades", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Organization.Grades", "HR Director", SeniorHr),
        ("PUT Organization.UpdateCompany", "HR Director", SeniorHr),
        ("POST OrganizationStructureImport.Commit", "HR Director", SeniorHr),
        ("POST OrganizationStructureImport.CommitBatch", "HR Director", SeniorHr),
        ("POST OrganizationStructureImport.CreateDryRunBatch", "HR Director", SeniorHr),
        ("GET OrganizationStructureImport.GetBatch", "HR Officer,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET OrganizationStructureImport.GetBatch", "HR Director", SeniorHr),
        ("POST OrganizationStructureImport.Preview", "HR Director", SeniorHr),
        ("GET OrganizationStructureImport.Template", "HR Officer,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET OrganizationStructureImport.Template", "HR Director", SeniorHr),
        ("POST Overtime.Approve", "HR Director", SeniorHr),
        ("GET Overtime.Budgets", "HR Officer,Manager,Supervisor", AggregateOnly),
        ("GET Overtime.Budgets", "HR Director", SeniorHr),
        ("POST Overtime.CreateCompOffConversion", "HR Director", SeniorHr),
        ("POST Overtime.CreatePolicy", "HR Director", SeniorHr),
        ("POST Overtime.CreateType", "HR Director", SeniorHr),
        ("POST Overtime.DetectFromAttendance", "HR Director", SeniorHr),
        ("POST Overtime.DetectFromAttendance", "HR Officer", HrOfficerFilesOnBehalf),
        ("GET Overtime.PayrollReview", "Finance Approver", PayrollFinanceTier),
        ("GET Overtime.PayrollReview", "HR Director", SeniorHr),
        ("POST Overtime.Reject", "HR Director", SeniorHr),
        ("POST PIP.AddCheckIn", "HR Director", SeniorHr),
        ("POST PIP.Create", "HR Director", SeniorHr),
        ("GET PIP.TerminationQueue", "HR Director", SeniorHr),
        ("PUT PIP.Update", "HR Director", SeniorHr),
        ("POST PIP.UpdateStatus", "HR Director", SeniorHr),
        ("GET Payroll.AiValidation", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.AiValidation", "HR Director", SeniorHr),
        ("GET Payroll.AuditIntegrity", "HR Manager,Payroll Manager,Payroll Officer,Finance Approver", PayrollFinanceTier),
        ("GET Payroll.AuditIntegrity", "HR Director", SeniorHr),
        ("GET Payroll.CostCenterAllocation", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.CostCenterAllocation", "HR Director", SeniorHr),
        ("GET Payroll.EmployeeSalariesImportTemplate", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.EmployeeSalariesImportTemplate", "HR Director", SeniorHr),
        ("GET Payroll.GetRunPopulation", "HR Director", SeniorHr),
        ("GET Payroll.GetSalaryStructure", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.GetSalaryStructure", "HR Director", SeniorHr),
        ("GET Payroll.GlJournal", "Payroll Officer,Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.GlJournal", "HR Director", SeniorHr),
        ("GET Payroll.ListEmployeeSalaries", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.ListEmployeeSalaries", "HR Director", SeniorHr),
        ("GET Payroll.ListEmployeeSalaryStructures", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.ListEmployeeSalaryStructures", "HR Director", SeniorHr),
        ("GET Payroll.ListEosb", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.ListEosb", "HR Director", SeniorHr),
        ("GET Payroll.ListGroups", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.ListGroups", "HR Director", SeniorHr),
        ("GET Payroll.ListPaymentBatches", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.ListPaymentBatches", "HR Director", SeniorHr),
        ("GET Payroll.ListPayrollCompanies", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.ListPayrollCompanies", "HR Director", SeniorHr),
        ("GET Payroll.ListPayslips", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.ListPayslips", "HR Director", SeniorHr),
        ("GET Payroll.ListRunApprovals", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.ListRunApprovals", "HR Director", SeniorHr),
        ("GET Payroll.ListRuns", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.ListRuns", "HR Director", SeniorHr),
        ("GET Payroll.ListValidationOverrides", "Payroll Officer", PayrollFinanceTier),
        ("GET Payroll.ListValidationOverrides", "HR Director", SeniorHr),
        ("GET Payroll.PaymentRecords", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.PaymentRecords", "HR Director", SeniorHr),
        ("GET Payroll.PayrollOverview", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.PayrollOverview", "HR Director", SeniorHr),
        ("GET Payroll.PayrollReadiness", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.PayrollReadiness", "HR Director", SeniorHr),
        ("GET Payroll.Register", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.Register", "HR Director", SeniorHr),
        ("GET Payroll.ReportSummary", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.ReportSummary", "HR Director", SeniorHr),
        ("GET Payroll.SalaryStructures", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.SalaryStructures", "HR Director", SeniorHr),
        ("GET Payroll.Slips", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.Slips", "HR Director", SeniorHr),
        ("GET Payroll.StructuresImportTemplate", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET Payroll.StructuresImportTemplate", "HR Director", SeniorHr),
        ("GET PayslipTemplates.Get", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET PayslipTemplates.Get", "HR Director", SeniorHr),
        ("GET PayslipTemplates.List", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET PayslipTemplates.List", "HR Director", SeniorHr),
        ("GET PayslipTemplates.Versions", "Finance Approver,Auditor", PayrollFinanceTier),
        ("GET PayslipTemplates.Versions", "HR Director", SeniorHr),
        ("POST Positions.Create", "HR Director", SeniorHr),
        ("POST Positions.Freeze", "HR Director", SeniorHr),
        ("GET Positions.Get", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Positions.Get", "HR Director", SeniorHr),
        ("GET Positions.List", "Compliance Officer,Recruiter,HR Assistant", OrgReadByDesign),
        ("GET Positions.List", "HR Director", SeniorHr),
        ("POST Positions.Reopen", "HR Director", SeniorHr),
        ("PUT Positions.Update", "HR Director", SeniorHr),
        ("POST Probation.Create", "HR Director", SeniorHr),
        ("POST Probation.HrDecision", "HR Director", SeniorHr),
        ("POST Probation.ManagerReview", "HR Director", SeniorHr),
        ("POST Recommendations.ApproveBonus", "HR Director", SeniorHr),
        ("POST Recommendations.ApproveIncrement", "HR Director", SeniorHr),
        ("POST Recommendations.ApprovePromotion", "HR Director", SeniorHr),
        ("POST Recommendations.CreateBonus", "HR Director", SeniorHr),
        ("POST Recommendations.CreateIncrement", "HR Director", SeniorHr),
        ("POST Recommendations.CreatePromotion", "HR Director", SeniorHr),
        ("GET Recommendations.ImplementationQueue", "HR Director", SeniorHr),
        ("POST RecruitmentAi.InterviewQuestions", "Recruiter", OwnModule),
        ("POST RecruitmentAi.InterviewQuestions", "HR Director", SeniorHr),
        ("POST RecruitmentAi.JobDescription", "Recruiter", OwnModule),
        ("POST RecruitmentAi.JobDescription", "HR Director", SeniorHr),
        ("POST RecruitmentAi.Screen", "Recruiter", OwnModule),
        ("POST RecruitmentAi.Screen", "HR Director", SeniorHr),
        ("GET RecruitmentReports.AIInsights", "Recruiter", OwnModule),
        ("GET RecruitmentReports.AIInsights", "HR Director", SeniorHr),
        ("GET RecruitmentReports.OpenPositions", "HR Director", SeniorHr),
        ("GET RecruitmentReports.PipelineSummary", "HR Director", SeniorHr),
        ("GET RecruitmentReports.SourceEffectiveness", "HR Director", SeniorHr),
        ("GET RecruitmentReports.TimeToHire", "HR Director", SeniorHr),
        ("POST Requisitions.Approve", "HR Director", SeniorHr),
        ("POST Requisitions.Create", "Recruiter", OwnModule),
        ("POST Requisitions.Create", "HR Director", SeniorHr),
        ("POST Requisitions.Reject", "HR Director", SeniorHr),
        ("POST Requisitions.Submit", "Recruiter", OwnModule),
        ("POST Requisitions.Submit", "HR Director", SeniorHr),
        ("PUT Requisitions.Update", "Recruiter", OwnModule),
        ("PUT Requisitions.Update", "HR Director", SeniorHr),
        ("POST Reviews.ComputeAttendance", "HR Director", SeniorHr),
        ("GET Reviews.ListAppeals", "HR Director", SeniorHr),
        ("POST Reviews.RespondToAppeal", "HR Director", SeniorHr),
        ("POST ScorecardTemplates.Create", "HR Director", SeniorHr),
        ("DELETE ScorecardTemplates.Delete", "HR Director", SeniorHr),
        ("PUT ScorecardTemplates.Update", "HR Director", SeniorHr),
        ("POST SetupAssistant.Apply", "HR Director", SeniorHr),
        ("POST SetupAssistant.Preview", "HR Director", SeniorHr),
        ("GET StatutoryRules.List", "Payroll Manager,Finance Approver", PayrollFinanceTier),
        ("GET TenantHrConfig.Get", "HR Officer,Compliance Officer,Recruiter,HR Assistant,Auditor", OrgReadByDesign),
        ("GET TenantHrConfig.Get", "HR Director", SeniorHr),
        ("POST VisaTracking.Create", "Compliance Officer", OwnModule),
        ("POST VisaTracking.Create", "HR Director", SeniorHr),
        ("POST VisaTracking.CreatePassport", "Compliance Officer", OwnModule),
        ("POST VisaTracking.CreatePassport", "HR Director", SeniorHr),
        ("POST VisaTracking.CreateRenewal", "Compliance Officer", OwnModule),
        ("POST VisaTracking.CreateRenewal", "HR Director", SeniorHr),
        ("POST VisaTracking.CreateWorkPermit", "Compliance Officer", OwnModule),
        ("POST VisaTracking.CreateWorkPermit", "HR Director", SeniorHr),
        ("GET VisaTracking.Get", "Compliance Officer", OwnModule),
        ("GET VisaTracking.Get", "Auditor", OrgReadByDesign),
        ("GET VisaTracking.Get", "HR Director", SeniorHr),
        ("GET VisaTracking.List", "Compliance Officer", OwnModule),
        ("GET VisaTracking.List", "Auditor", OrgReadByDesign),
        ("GET VisaTracking.List", "HR Director", SeniorHr),
        ("GET VisaTracking.ListPassports", "Compliance Officer", OwnModule),
        ("GET VisaTracking.ListPassports", "Auditor", OrgReadByDesign),
        ("GET VisaTracking.ListPassports", "HR Director", SeniorHr),
        ("GET VisaTracking.ListRenewals", "Compliance Officer", OwnModule),
        ("GET VisaTracking.ListRenewals", "Auditor", OrgReadByDesign),
        ("GET VisaTracking.ListRenewals", "HR Director", SeniorHr),
        ("GET VisaTracking.ListWorkPermits", "Compliance Officer", OwnModule),
        ("GET VisaTracking.ListWorkPermits", "Auditor", OrgReadByDesign),
        ("GET VisaTracking.ListWorkPermits", "HR Director", SeniorHr),
        ("PUT VisaTracking.Update", "Compliance Officer", OwnModule),
        ("PUT VisaTracking.Update", "HR Director", SeniorHr),
        ("PATCH VisaTracking.UpdateRenewalStatus", "Compliance Officer", OwnModule),
        ("PATCH VisaTracking.UpdateRenewalStatus", "HR Director", SeniorHr),
        ("POST WorkforcePlanning.Create", "Recruiter", OwnModule),
        ("POST WorkforcePlanning.Create", "HR Director", SeniorHr),
        ("DELETE WorkforcePlanning.Delete", "HR Director", SeniorHr),
        ("PATCH WorkforcePlanning.UpdateStatus", "Recruiter", OwnModule),
        ("PATCH WorkforcePlanning.UpdateStatus", "HR Director", SeniorHr),
    };

    /// <summary>
    /// Roles a gate NAMES that can never pass it (they hold none of its keys), each with a decision for the owner:
    /// GRANT the key, DROP the role from the role list, or KEEP it as deliberate (with why). Nothing here grants a
    /// permission; this is a to-do list for the owner.
    /// "GRANT none (prefer explicit gate)" marks a resolver mis-mapping, where an explicit [HasPermission] is the fix.
    /// </summary>
    internal static readonly (string Endpoint, string Roles, string Decision)[] NamedButLocked =
    {
        ("POST AIAssistant.AcknowledgeInsight", "HR Manager,HR Officer", "GRANT ai.query: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST AIAssistant.ComputeRiskScores", "HR Manager", "GRANT ai.query: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET AIAssistant.ListInsights", "Finance Approver,HR Manager,HR Officer,Payroll Manager", "GRANT ai.insights_view: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET AIAssistant.PayrollValidation", "HR Manager,Payroll Manager", "GRANT ai.insights_view: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET AIAssistant.QueryHistory", "HR Manager", "GRANT ai.insights_view: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET AIAssistant.RiskScores", "HR Manager", "GRANT ai.insights_view: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST AIAssistant.RunPayrollValidation", "HR Manager,Payroll Manager", "GRANT ai.query: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Advances.Approve", "Manager", "DROP Manager: salary-advance decisions are the finance tier; Manager holds loans.read only."),
        ("PATCH Advances.Reject", "Manager", "DROP Manager: salary-advance decisions are the finance tier; Manager holds loans.read only."),
        ("POST Applications.AcceptOffer", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Applications.AddNote", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Applications.Advance", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Applications.Apply", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Applications.DeclineOffer", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Applications.GenerateOffer", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Applications.Get", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Applications.GetOfferHtml", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Applications.Kanban", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Applications.List", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Applications.RecordFeedback", "HR Manager,HR Officer,Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Applications.Reject", "HR Manager,HR Officer", "GRANT recruitment.approve: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Applications.ScheduleInterview", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Applications.SendOffer", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST ApprovalWorkflows.Decide", "Payroll Officer", "KEEP Payroll Officer (deliberate): the bare role holds approvals.read only, and the ManagerPortal access mode adds approvals.decide on purpose. CanDecideRequestAsync then limits them to steps routed to the Payroll Officer role or assigned to them by name. Do not drop."),
        ("POST Assessments.CreateTemplate", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Assessments.List", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Assessments.RecordResult", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Assessments.Send", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Attendance.CreateDevice", "HR Officer", "DROP HR Officer: device keys and punch import feed payroll; HR-manager tier since #180."),
        ("DELETE Attendance.DeleteDevice", "HR Officer", "GRANT attendance.delete: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Attendance.GenerateDeviceKey", "HR Officer", "DROP HR Officer: device keys and punch import feed payroll; HR-manager tier since #180."),
        ("POST Attendance.Import", "HR Officer", "DROP HR Officer: device keys and punch import feed payroll; HR-manager tier since #180."),
        ("POST Attendance.Process", "HR Officer", "GRANT attendance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Attendance.ProcessInBackground", "HR Officer", "GRANT attendance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Attendance.Reprocess", "HR Officer", "GRANT attendance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Attendance.Sync", "HR Officer", "DROP HR Officer: device keys and punch import feed payroll; HR-manager tier since #180."),
        ("POST Attendance.TestConnection", "HR Officer", "DROP HR Officer: device keys and punch import feed payroll; HR-manager tier since #180."),
        ("PUT Attendance.UpdateDevice", "HR Officer", "DROP HR Officer: device keys and punch import feed payroll; HR-manager tier since #180."),
        ("POST Benefits.AddContribution", "Finance", "DROP Finance: benefits contribution/deduction writes are the HR-manager tier since #180."),
        ("POST Benefits.LinkPayrollDeduction", "Finance", "DROP Finance: benefits contribution/deduction writes are the HR-manager tier since #180."),
        ("GET Bonuses.AuditReport", "Finance", "GRANT payroll.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Bonuses.GetPayrollPendingBonuses", "Finance", "GRANT payroll.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Candidates.Blacklist", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Candidates.Create", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Candidates.Get", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Candidates.List", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PUT Candidates.Update", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET CompanyComplianceProfiles.List", "HR Manager", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET CompanyComplianceProfiles.Readiness", "HR Manager", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET CompanyTaxPolicies.List", "Auditor,HR Director", "GRANT payroll.rates.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET ComplianceReports.AIInsights", "HR Manager", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST ComplianceReports.CreateDocType", "HR Manager", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET ComplianceReports.EmployeeIdentityIntegrity", "HR Manager", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Contracts.Create", "HR Manager", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Contracts.CreateTemplate", "HR Manager", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Contracts.Get", "HR Manager,HR Officer", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Contracts.GetTemplate", "HR Manager,HR Officer", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Contracts.List", "HR Manager,HR Officer", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Contracts.ListTemplates", "HR Manager,HR Officer", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Contracts.Supersede", "HR Manager", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Contracts.UpdateStatus", "HR Manager", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET CountryPack.GetAvailable", "Auditor", "GRANT localization.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PUT Employees.UpdateEmployee", "Payroll Officer", "DROP Payroll Officer: employee record edits are HR; payroll changes go through salary/bank change requests."),
        ("POST Encashment.PayrollApprove", "Payroll Officer", "DROP Payroll Officer: maker role; payroll decisions belong to the payroll.approve tier."),
        ("POST Goals.Create", "Employee", "DROP Employee: AuthSeeder says goals are set by the line manager or HR (no performance.write for employees)."),
        ("POST Goals.Create", "HR Officer", "GRANT performance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("DELETE Goals.Delete", "Employee", "DROP Employee: AuthSeeder says goals are set by the line manager or HR (no performance.write for employees)."),
        ("DELETE Goals.Delete", "HR Officer", "GRANT performance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PUT Goals.Update", "Employee", "DROP Employee: AuthSeeder says goals are set by the line manager or HR (no performance.write for employees)."),
        ("PUT Goals.Update", "HR Officer", "GRANT performance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Interviews.Cancel", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Interviews.Complete", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Interviews.Get", "HR Manager,HR Officer,Manager", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Interviews.GetFeedback", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Interviews.List", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Interviews.Schedule", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Interviews.SubmitFeedback", "HR Manager,HR Officer,Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Loans.AddApprovalStep", "HR Director", "GRANT loans.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Loans.DecideApproval", "HR Director", "GRANT loans.approve: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Loans.DecideLoanChange", "HR Director", "GRANT loans.approve: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Loans.RequestLoanChange", "HR Director", "GRANT loans.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Offers.Accept", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Offers.AddApproval", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Offers.ApproverOptions", "HR Manager", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Offers.Create", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Offers.DecideApproval", "HR Manager", "GRANT recruitment.approve: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Offers.Decline", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Offers.Download", "HR Manager", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Offers.Get", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Offers.List", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Offers.PlacementOptions", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Offers.Send", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Onboarding.CreateBulkFromChecklist", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Onboarding.CreateChecklist", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Onboarding.CreateTask", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Onboarding.ListChecklists", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Onboarding.ListTasks", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Onboarding.ListTemplateTasks", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Onboarding.Summary", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH Onboarding.UpdateTaskStatus", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Onboarding.UpsertTemplateTask", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Openings.Close", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Openings.Create", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Openings.Import", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PUT Openings.Update", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Organization.CreateDepartment", "HR Officer", "GRANT organization.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Organization.CreateDesignation", "HR Officer", "GRANT organization.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Organization.Departments", "Manager", "GRANT organization.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Organization.Designations", "Manager", "GRANT organization.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Overtime.Approve", "Supervisor", "DROP Supervisor: overtime pay decisions sit with Manager, which holds overtime.approve."),
        ("GET Overtime.Budgets", "Auditor,Finance Approver,Payroll Officer", "GRANT overtime.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Overtime.CreatePolicy", "Payroll Officer", "DROP Payroll Officer: overtime policy and types are HR configuration."),
        ("POST Overtime.CreateType", "Payroll Officer", "DROP Payroll Officer: overtime policy and types are HR configuration."),
        ("POST Overtime.DetectFromAttendance", "Payroll Officer", "GRANT overtime.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Overtime.Reject", "Supervisor", "DROP Supervisor: overtime pay decisions sit with Manager, which holds overtime.approve."),
        ("POST PIP.Create", "HR Officer", "GRANT performance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET PIP.TerminationQueue", "HR Officer", "GRANT performance.approve: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PUT PIP.Update", "HR Officer", "GRANT performance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Payroll.DownloadRunPdfBundle", "HR Manager,Payroll Manager,Payroll Officer", "GRANT payroll.export: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Payroll.DownloadSlipPdf", "HR Manager,Payroll Manager,Payroll Officer", "GRANT payroll.export: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Payroll.ExportEmployeeSalaries", "HR Manager,Payroll Manager,Payroll Officer", "GRANT payroll.export: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Payroll.ExportStructures", "HR Manager,Payroll Manager,Payroll Officer", "GRANT payroll.export: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Probation.Create", "HR Officer", "GRANT performance.cycle_manage: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Recommendations.ImplementationQueue", "Payroll Manager", "GRANT performance.approve: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST RecruitmentAi.InterviewQuestions", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST RecruitmentAi.JobDescription", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST RecruitmentAi.Screen", "HR Manager,HR Officer", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET RecruitmentReports.AIInsights", "HR Manager", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET RecruitmentReports.OpenPositions", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET RecruitmentReports.PipelineSummary", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET RecruitmentReports.SourceEffectiveness", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET RecruitmentReports.TimeToHire", "HR Manager,HR Officer", "GRANT recruitment.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Requisitions.Approve", "HR Manager", "GRANT recruitment.approve: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Requisitions.Create", "HR Manager,HR Officer,Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Requisitions.Reject", "HR Manager", "GRANT recruitment.approve: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Requisitions.Submit", "HR Manager,HR Officer,Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PUT Requisitions.Update", "HR Manager,HR Officer,Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET SetupSettings.GetGCCSettings", "HR Manager", "DROP HR Manager: security.manage is the Admin-only tenant settings tier."),
        ("GET SetupSettings.ListNotificationTemplates", "HR Manager", "DROP HR Manager: security.manage is the Admin-only tenant settings tier."),
        ("POST Shifts.AiPlan", "HR Manager", "GRANT shifts.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Shifts.Assign", "HR Manager,HR Officer,Manager,Supervisor", "GRANT shifts.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Shifts.AutoPlan", "HR Manager", "GRANT shifts.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Shifts.CommitPlan", "HR Manager", "GRANT shifts.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST Shifts.CreateDefinition", "HR Manager", "GRANT shifts.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("DELETE Shifts.DeleteDefinition", "HR Manager", "GRANT shifts.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET Shifts.GetPolicy", "HR Manager", "GRANT shifts.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("DELETE Shifts.RemoveAssignment", "HR Manager,HR Officer,Manager,Supervisor", "GRANT shifts.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PUT Shifts.UpdateDefinition", "HR Manager", "GRANT shifts.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PUT Shifts.UpsertPolicy", "HR Manager", "GRANT shifts.manage: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET StatutoryRules.List", "Auditor,HR Manager", "GRANT payroll.rates.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST VisaTracking.Create", "HR Manager,HR Officer", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST VisaTracking.CreatePassport", "HR Manager,HR Officer", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST VisaTracking.CreateRenewal", "HR Manager,HR Officer", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST VisaTracking.CreateWorkPermit", "HR Manager,HR Officer", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET VisaTracking.Get", "HR Manager,HR Officer", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET VisaTracking.List", "HR Manager,HR Officer", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET VisaTracking.ListPassports", "HR Manager,HR Officer", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET VisaTracking.ListRenewals", "HR Manager,HR Officer", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("GET VisaTracking.ListWorkPermits", "HR Manager,HR Officer", "GRANT compliance.read: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PUT VisaTracking.Update", "HR Manager,HR Officer", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH VisaTracking.UpdateRenewalStatus", "HR Manager,HR Officer", "GRANT compliance.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("POST WorkforcePlanning.Create", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("DELETE WorkforcePlanning.Delete", "HR Manager", "GRANT recruitment.delete: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
        ("PATCH WorkforcePlanning.UpdateStatus", "HR Manager", "GRANT recruitment.write: owner decision. The gate names these roles for this work but their seeded bundles omit the key."),
    };
}
