// Two-step sign-in strings, merged into i18n as the `mfa` namespace.
// Kept import-free so tests can check EN/AR key parity under node.

export const mfaEn = {
  challengeTitle: 'Enter your sign-in code',
  challengeBody: 'Open your authenticator app and enter the 6-digit code for {{email}}.',
  codeLabel: '6-digit sign-in code',
  verify: 'Verify and sign in',
  expiresIn: 'This code request expires in {{time}}',
  backToSignIn: 'Back to sign in',
  attemptsLeft: 'Attempts left: {{count}}',
  errors: {
    wrongCode: "That code didn't work. Check the code in your authenticator app and try again.",
    notAccepted: 'Not accepted. If this keeps happening, sign in again.',
    attemptLimit: 'Too many wrong codes. For your security, go back and sign in again to get a new code request.',
    expired: 'This code request has expired. Go back and sign in again.',
    rateLimited: 'Too many tries in a short time. Wait a minute, then try again.',
    network: "Can't reach KynexOne. Check your connection and try again.",
    server: 'Something went wrong on our side. Try again in a moment.',
  },
  enrolTitle: 'Set up two-step sign-in',
  enrolRequiredBody:
    'Your role requires a code from an authenticator app each time you sign in. Setup takes about a minute.',
  enrolOptionalBody: 'Add a code from an authenticator app to your sign-in. Setup takes about a minute.',
  step1: '1. Add KynexOne to your authenticator app',
  openAuthenticator: 'Open authenticator app',
  noAuthenticator:
    'No authenticator app opened. Install one (for example Microsoft Authenticator or Google Authenticator), or add an account by hand with the setup key below.',
  manualKeyHelp: 'Or add an account by hand in your authenticator app and enter this setup key:',
  setupKeyLabel: 'Setup key',
  longPressToCopy: 'Press and hold the key to copy it.',
  clipboardSync: 'Copying puts the key on the clipboard, which may sync to your other devices.',
  replaceExisting: 'If you already added a KynexOne entry, delete it and add this key.',
  shareKey: 'Share key',
  keyPrivate: 'Keep this key private. Anyone who has it can create your sign-in codes.',
  step2: '2. Enter the 6-digit code your app shows',
  enable: 'Turn on two-step sign-in',
  setupExpiresIn: 'This setup expires in {{time}}',
  loadingSetup: 'Preparing your setup key…',
  setupExpired: 'This setup has expired. Start again to get a new setup key.',
  setupExpiredSignIn: 'This setup has expired. Go back and sign in again to get a new setup key.',
  startAgain: 'Start again',
  retry: 'Try again',
  cancel: 'Cancel',
  doneTitle: 'Two-step sign-in is on',
  doneSignInAgain: 'Sign in again with your password and a code from your authenticator app.',
  continue: 'Continue',
  recoveryTitle: 'Save your recovery codes',
  recoveryBody:
    'Each code works once if you lose access to your authenticator app. Store them somewhere safe; they will not be shown again.',
  shareCodes: 'Share codes',
  savedCodes: "I've saved these codes",
  bannerWithDate: 'Your role requires two-step sign-in from {{date}}. Set it up now.',
  bannerNoDate: 'Your role requires two-step sign-in. Set it up now.',
  bannerEnforced: 'Your role now requires two-step sign-in. Set it up now to keep using KynexOne.',
  bannerAction: 'Set up now',
  bannerDismiss: 'Not now',
  alreadyOn: 'Two-step sign-in is already on for your account.',
};

export const mfaAr: typeof mfaEn = {
  challengeTitle: 'أدخل رمز تسجيل الدخول',
  challengeBody: 'افتح تطبيق المصادقة وأدخل الرمز المكوّن من 6 أرقام للحساب {{email}}.',
  codeLabel: 'رمز تسجيل الدخول المكوّن من 6 أرقام',
  verify: 'تحقّق وسجّل الدخول',
  expiresIn: 'ينتهي طلب الرمز هذا خلال {{time}}',
  backToSignIn: 'العودة إلى تسجيل الدخول',
  attemptsLeft: 'المحاولات المتبقية: {{count}}',
  errors: {
    wrongCode: 'هذا الرمز غير صحيح. تحقّق من الرمز في تطبيق المصادقة وحاول مرة أخرى.',
    notAccepted: 'لم يُقبل. إذا تكرر ذلك، سجّل الدخول من جديد.',
    attemptLimit: 'أُدخلت رموز خاطئة عدة مرات. لحمايتك، ارجع وسجّل الدخول من جديد للحصول على طلب رمز جديد.',
    expired: 'انتهت صلاحية طلب الرمز. ارجع وسجّل الدخول من جديد.',
    rateLimited: 'محاولات كثيرة خلال وقت قصير. انتظر دقيقة ثم حاول مرة أخرى.',
    network: 'تعذّر الاتصال بـ KynexOne. تحقّق من اتصالك وحاول مرة أخرى.',
    server: 'حدث خطأ من جهتنا. حاول مرة أخرى بعد قليل.',
  },
  enrolTitle: 'إعداد تسجيل الدخول بخطوتين',
  enrolRequiredBody: 'يتطلب دورك إدخال رمز من تطبيق المصادقة في كل مرة تسجّل فيها الدخول. يستغرق الإعداد دقيقة تقريبًا.',
  enrolOptionalBody: 'أضف رمزًا من تطبيق المصادقة إلى تسجيل دخولك. يستغرق الإعداد دقيقة تقريبًا.',
  step1: '1. أضف KynexOne إلى تطبيق المصادقة',
  openAuthenticator: 'فتح تطبيق المصادقة',
  noAuthenticator:
    'لم يُفتح أي تطبيق مصادقة. ثبّت تطبيقًا (مثل Microsoft Authenticator أو Google Authenticator)، أو أضف حسابًا يدويًا باستخدام مفتاح الإعداد أدناه.',
  manualKeyHelp: 'أو أضف حسابًا يدويًا في تطبيق المصادقة وأدخل مفتاح الإعداد هذا:',
  setupKeyLabel: 'مفتاح الإعداد',
  longPressToCopy: 'اضغط مطولًا على المفتاح لنسخه.',
  clipboardSync: 'يضع النسخ المفتاح في الحافظة، وقد تتم مزامنتها مع أجهزتك الأخرى.',
  replaceExisting: 'إذا كنت قد أضفت إدخالًا لـ KynexOne من قبل، فاحذفه وأضف هذا المفتاح.',
  shareKey: 'مشاركة المفتاح',
  keyPrivate: 'احتفظ بهذا المفتاح سرًا. يستطيع أي شخص يملكه إنشاء رموز تسجيل الدخول الخاصة بك.',
  step2: '2. أدخل الرمز المكوّن من 6 أرقام الذي يظهر في التطبيق',
  enable: 'تفعيل تسجيل الدخول بخطوتين',
  setupExpiresIn: 'ينتهي هذا الإعداد خلال {{time}}',
  loadingSetup: 'جارٍ تجهيز مفتاح الإعداد…',
  setupExpired: 'انتهت صلاحية هذا الإعداد. ابدأ من جديد للحصول على مفتاح إعداد جديد.',
  setupExpiredSignIn: 'انتهت صلاحية هذا الإعداد. ارجع وسجّل الدخول من جديد للحصول على مفتاح إعداد جديد.',
  startAgain: 'البدء من جديد',
  retry: 'حاول مرة أخرى',
  cancel: 'إلغاء',
  doneTitle: 'تم تفعيل تسجيل الدخول بخطوتين',
  doneSignInAgain: 'سجّل الدخول من جديد بكلمة المرور ورمز من تطبيق المصادقة.',
  continue: 'متابعة',
  recoveryTitle: 'احفظ رموز الاسترداد',
  recoveryBody:
    'يعمل كل رمز مرة واحدة إذا فقدت الوصول إلى تطبيق المصادقة. احفظها في مكان آمن؛ لن تُعرض مرة أخرى.',
  shareCodes: 'مشاركة الرموز',
  savedCodes: 'حفظت هذه الرموز',
  bannerWithDate: 'يتطلب دورك تسجيل الدخول بخطوتين اعتبارًا من {{date}}. أعدّه الآن.',
  bannerNoDate: 'يتطلب دورك تسجيل الدخول بخطوتين. أعدّه الآن.',
  bannerEnforced: 'يتطلب دورك الآن تسجيل الدخول بخطوتين. أعدّه الآن لمواصلة استخدام KynexOne.',
  bannerAction: 'الإعداد الآن',
  bannerDismiss: 'ليس الآن',
  alreadyOn: 'تسجيل الدخول بخطوتين مفعّل بالفعل لحسابك.',
};
