// Employee sign-in and first sign-in (welcome code) strings, merged into i18n as the `signin`
// namespace. Wording follows the Saudi HR / Arabic SME copy deck: in Arabic the code is «رمز التفعيل»
// and the company's sign-in ID is «معرّف الشركة». Import-free so tests can check EN/AR key parity.

export const welcomeEn = {
  email: 'Email',
  emailPlaceholder: 'name@company.com',
  workEmail: 'Work email',
  password: 'Password',
  passwordPlaceholder: 'Enter your password',
  companyId: 'Company ID',
  companyIdNeeded: "We couldn't find your company from your email. Enter your company ID. HR can tell you what it is.",
  companyIdRequired: 'Enter your company ID.',
  emailRequired: 'Enter your work email.',
  passwordRequired: 'Enter your password.',
  firstTime: 'First time? Use your welcome code',
  title: 'Welcome',
  kicker: 'First sign-in',
  intro: 'Enter your work email and the welcome code from your sign-in slip.',
  code: 'Welcome code',
  codeHint: 'The 8-digit code on your sign-in slip.',
  codeShape: 'The welcome code is 8 digits. Check your sign-in slip.',
  continue: 'Continue',
  notYourEmail: 'Not your email?',
  choosePassword: 'Choose a password',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  atLeast: 'At least {{n}} characters',
  notPersonal: "Doesn't contain your name or email",
  englishLetters: 'Use English letters so you can sign in from any keyboard.',
  save: 'Save password and sign in',
  saving: 'Signing in…',
  lookedLikeCode: "That looks like a welcome code. Let's set your password.",
  passwordSaved: 'Your password is saved. Sign in with your email and new password.',
  forgotFooter: 'Forgot your password? Ask HR for a new welcome code.',
  haveAPassword: 'I already have a password',
  signedInTitle: 'Signed in',
  resetNotice: "HR gave you a new sign-in code on {{date}}. If you didn't ask for it, tell HR.",
  language: 'Language',
  hideMessage: 'Hide this message',
  noEmail: 'Forgot your password? Ask HR for a new welcome code.',
  forgot: {
    eyebrow: 'Account recovery',
    title: 'Reset your password',
    subtitle: 'Enter your work email. We will send a secure reset link if email is set up for your company.',
    send: 'Send reset link',
    sentTitle: 'Check your email',
    sentBody: 'If that account exists, we sent a secure password-reset link. Open the link to continue.',
    failedTitle: 'Request failed',
    failedBody: 'We could not request a reset link. Try again later.',
    privacy: 'For your privacy, KynexOne does not confirm whether an email address exists.',
  },
  errors: {
    codeInvalid: "Email and code don't match. Check both on your sign-in slip.",
    codeGone: 'This code no longer works. It may have expired or already been used. Ask HR for a new one.',
    passwordRules: "Your password doesn't meet the rules above.",
    companyIdNeeded: "We couldn't find your company from your email. Enter your company ID. HR can tell you what it is.",
    tooManyTries: 'Too many tries. Wait a few minutes and try again.',
    signOutFirst: 'Sign out of KynexOne on this device first.',
    planFull: "Your company's KynexOne plan is full. Ask HR.",
    generic: 'Something went wrong. Please try again.',
    network: "Can't reach KynexOne. Check your connection and try again.",
  },
};

export const welcomeAr: typeof welcomeEn = {
  email: 'البريد الإلكتروني',
  emailPlaceholder: 'name@company.com',
  workEmail: 'البريد الإلكتروني الوظيفي',
  password: 'كلمة المرور',
  passwordPlaceholder: 'أدخل كلمة المرور',
  companyId: 'معرّف الشركة',
  companyIdNeeded: 'تعذّر التعرّف على شركتك من البريد الإلكتروني. يُرجى إدخال معرّف الشركة، ويمكن للموارد البشرية تزويدك به.',
  companyIdRequired: 'يُرجى إدخال معرّف الشركة.',
  emailRequired: 'يُرجى إدخال البريد الإلكتروني الوظيفي.',
  passwordRequired: 'يُرجى إدخال كلمة المرور.',
  firstTime: 'أول مرة؟ استخدم رمز التفعيل',
  title: 'مرحباً',
  kicker: 'أول تسجيل دخول',
  intro: 'أدخل البريد الإلكتروني الوظيفي ورمز التفعيل الموجود في ورقة تسجيل الدخول.',
  code: 'رمز التفعيل',
  codeHint: 'الرمز المكوّن من 8 أرقام في ورقة تسجيل الدخول.',
  codeShape: 'رمز التفعيل مكوّن من 8 أرقام. يُرجى التحقق من ورقة تسجيل الدخول.',
  continue: 'متابعة',
  notYourEmail: 'ليس بريدك؟',
  choosePassword: 'اختر كلمة المرور',
  showPassword: 'إظهار كلمة المرور',
  hidePassword: 'إخفاء كلمة المرور',
  atLeast: '{{n}} خانات على الأقل',
  notPersonal: 'لا تحتوي على اسمك أو بريدك الإلكتروني',
  englishLetters: 'استخدم أحرفاً إنجليزية ليسهل الدخول من أي لوحة مفاتيح.',
  save: 'حفظ كلمة المرور وتسجيل الدخول',
  saving: 'جارٍ تسجيل الدخول…',
  lookedLikeCode: 'يبدو أن هذا رمز التفعيل. لنُكمل إنشاء كلمة المرور.',
  passwordSaved: 'تم حفظ كلمة المرور. سجّل الدخول ببريدك الإلكتروني وكلمة المرور الجديدة.',
  forgotFooter: 'نسيت كلمة المرور؟ اطلب رمز تفعيل جديد من الموارد البشرية.',
  haveAPassword: 'لديّ كلمة مرور بالفعل',
  signedInTitle: 'تم تسجيل الدخول',
  resetNotice: 'أصدرت الموارد البشرية لك رمز دخول جديداً بتاريخ {{date}}. إذا لم تطلبه، يُرجى إبلاغ الموارد البشرية.',
  language: 'اللغة',
  hideMessage: 'إخفاء هذه الرسالة',
  noEmail: 'نسيت كلمة المرور؟ اطلب رمز تفعيل جديد من الموارد البشرية.',
  forgot: {
    eyebrow: 'استعادة الحساب',
    title: 'إعادة تعيين كلمة المرور',
    subtitle: 'أدخل بريدك الإلكتروني الوظيفي. سنرسل رابطاً آمناً لإعادة التعيين إذا كان البريد مُفعّلاً لشركتك.',
    send: 'إرسال رابط إعادة التعيين',
    sentTitle: 'تحقق من بريدك الإلكتروني',
    sentBody: 'إذا كان هذا الحساب موجوداً، فقد أرسلنا رابطاً آمناً لإعادة تعيين كلمة المرور. افتح الرابط للمتابعة.',
    failedTitle: 'تعذّر الطلب',
    failedBody: 'تعذّر طلب رابط إعادة التعيين. يُرجى المحاولة لاحقاً.',
    privacy: 'حفاظاً على خصوصيتك، لا يؤكد KynexOne وجود أي بريد إلكتروني.',
  },
  errors: {
    codeInvalid: 'البريد الإلكتروني والرمز غير متطابقين. يُرجى التحقق منهما في ورقة تسجيل الدخول.',
    codeGone: 'هذا الرمز لم يعد صالحاً، فقد تكون انتهت صلاحيته أو سبق استخدامه. يُرجى طلب رمز جديد من الموارد البشرية.',
    passwordRules: 'كلمة المرور لا تستوفي الشروط أعلاه.',
    companyIdNeeded: 'تعذّر التعرّف على شركتك من البريد الإلكتروني. يُرجى إدخال معرّف الشركة، ويمكن للموارد البشرية تزويدك به.',
    tooManyTries: 'محاولات كثيرة. يُرجى الانتظار بضع دقائق ثم المحاولة مرة أخرى.',
    signOutFirst: 'يُرجى تسجيل الخروج من KynexOne على هذا الجهاز أولاً.',
    planFull: 'اكتمل عدد المستخدمين في باقة KynexOne الخاصة بشركتك. يُرجى التواصل مع الموارد البشرية.',
    generic: 'حدث خطأ ما. يُرجى المحاولة مرة أخرى.',
    network: 'تعذّر الاتصال بـ KynexOne. يُرجى التحقق من الاتصال ثم المحاولة مرة أخرى.',
  },
};
