using Microsoft.EntityFrameworkCore;
using Zayra.Api.Domain.Entities;

namespace Zayra.Api.Models;

/// <summary>
/// W2-B — an employee expense claim: the reimbursement aggregate. Modelled on
/// <see cref="SalaryAdvance"/>/<see cref="AdvanceInstallment"/> (header + lines).
///
/// <para><b>Lifecycle.</b> Draft → Submitted (routed through the F1 approval router as
/// <c>EntityName = "ExpenseClaim"</c>) → Approved | Rejected → Scheduled (bound to one payroll run by
/// exactly one <see cref="PayrollAdjustment"/>) → Paid (that adjustment was consumed by a processed
/// run). The approval row is the source of truth for the decision; the claim's own status is a
/// projection of it that the service reconciles.</para>
///
/// <para><b>Money.</b> Single currency: the claim is stamped with its legal entity's
/// <c>DefaultCurrency</c> at creation and every line is in that currency. There is no per-line
/// currency field, on purpose — a field that is accepted and then ignored is worse than none.</para>
/// </summary>
public class ExpenseClaim : ITenantOwned, ICompanyScopedOperational
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid TenantId { get; set; }
    /// <summary>The employee's legal entity. Required: payroll pays per company.</summary>
    public Guid? CompanyId { get; set; }
    public int EmployeeId { get; set; }
    public string EmployeeName { get; set; } = string.Empty;
    /// <summary>Human reference, unique per tenant (EXP-2026-XXXXXX).</summary>
    public string ClaimNumber { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    /// <summary>ISO currency of every line — the legal entity's payroll currency at creation.</summary>
    public string Currency { get; set; } = string.Empty;
    public decimal TotalAmount { get; set; }
    public string Status { get; set; } = ExpenseClaimStatuses.Draft;

    public Guid? ApprovalRequestId { get; set; }
    public DateTime? SubmittedAtUtc { get; set; }
    public Guid? SubmittedByUserId { get; set; }
    public DateTime? DecidedAtUtc { get; set; }
    public string? RejectionReason { get; set; }

    /// <summary>The run the reimbursement is bound to (Scheduled/Paid).</summary>
    public Guid? PayrollRunId { get; set; }
    /// <summary>The ONE payroll adjustment that carries this claim (SourceType ExpenseClaim, SourceId = Id).</summary>
    public Guid? PayrollAdjustmentId { get; set; }
    public DateTime? ScheduledAtUtc { get; set; }
    public Guid? ScheduledByUserId { get; set; }
    public DateTime? PaidAtUtc { get; set; }

    /// <summary>Optimistic concurrency token — every state transition advances it.</summary>
    public int Version { get; set; }

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public Guid? CreatedBy { get; set; }
    public DateTime? UpdatedAtUtc { get; set; }
    public Guid? UpdatedBy { get; set; }

    public List<ExpenseClaimLine> Lines { get; set; } = new();
}

/// <summary>One receipt-level expense on a claim. Company-scoped like its header so a direct line
/// query (the report) is filtered exactly like the claim.</summary>
public class ExpenseClaimLine : ITenantOwned, ICompanyScopedOperational
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid TenantId { get; set; }
    public Guid? CompanyId { get; set; }
    public Guid ClaimId { get; set; }
    public int LineNumber { get; set; }
    public DateOnly ExpenseDate { get; set; }
    /// <summary>MasterDataValue.Code under the tenant's <c>ExpenseCategory</c> type.</summary>
    public string CategoryCode { get; set; } = string.Empty;
    public string CategoryName { get; set; } = string.Empty;
    public decimal Amount { get; set; }
    public string Description { get; set; } = string.Empty;

    // Receipt — the storage key is ALWAYS server-generated by IDocumentStorage (tenant-prefixed).
    public string? ReceiptStorageKey { get; set; }
    public string? ReceiptFileName { get; set; }
    public string? ReceiptContentType { get; set; }
    public long? ReceiptSizeBytes { get; set; }
    public DateTime? ReceiptUploadedAtUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAtUtc { get; set; }

    public ExpenseClaim? Claim { get; set; }
}

public static class ExpenseClaimStatuses
{
    public const string Draft = "Draft";
    public const string Submitted = "Submitted";
    public const string Approved = "Approved";
    public const string Rejected = "Rejected";
    public const string Scheduled = "Scheduled";
    public const string Paid = "Paid";
    public const string Cancelled = "Cancelled";

    public static readonly string[] All = { Draft, Submitted, Approved, Rejected, Scheduled, Paid, Cancelled };
}

/// <summary>Stable identifiers the expense module shares with approvals, payroll, GL and master data.</summary>
public static class ExpenseClaimConstants
{
    /// <summary>ApprovalRequest.EntityName / ApprovalWorkflow.EntityName.</summary>
    public const string ApprovalEntityName = "ExpenseClaim";
    /// <summary>PayrollAdjustment.SourceType — unique with (TenantId, SourceId) ⇒ one adjustment per claim.</summary>
    public const string AdjustmentSourceType = "ExpenseClaim";
    /// <summary>PayrollAdjustment.AdjustmentType. Payroll emits it as the earning component
    /// <c>ADJ_EXPENSE_REIMBURSEMENT</c> (source "Adjustment"), which the GL driver
    /// <c>EARN:EXPENSE_REIMBURSEMENT</c> matches exactly.</summary>
    public const string AdjustmentType = "Expense Reimbursement";
    public const string EarningComponentCode = "ADJ_EXPENSE_REIMBURSEMENT";
    public const string GlDriverKey = "EARN:EXPENSE_REIMBURSEMENT";
    /// <summary>MasterDataType.Code holding the tenant's expense categories.</summary>
    public const string CategoryMasterType = "ExpenseCategory";
}

internal static class ExpenseModelConfiguration
{
    public static void Configure(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ExpenseClaim>(entity =>
        {
            entity.ToTable("expense_claims");
            entity.HasKey(x => x.Id);
            entity.Property(x => x.TotalAmount).HasPrecision(14, 2);
            entity.Property(x => x.ClaimNumber).HasMaxLength(40);
            entity.Property(x => x.Title).HasMaxLength(200);
            entity.Property(x => x.Currency).HasMaxLength(3);
            entity.Property(x => x.Status).HasMaxLength(20);
            entity.Property(x => x.RejectionReason).HasMaxLength(1000);
            entity.Property(x => x.Version).IsConcurrencyToken();
            entity.HasIndex(x => new { x.TenantId, x.ClaimNumber }).IsUnique();
            entity.HasIndex(x => new { x.TenantId, x.EmployeeId, x.Status });
            entity.HasIndex(x => new { x.TenantId, x.CompanyId, x.Status });
            entity.HasIndex(x => new { x.TenantId, x.ApprovalRequestId });
            entity.HasMany(x => x.Lines).WithOne(x => x.Claim!).HasForeignKey(x => x.ClaimId).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<ExpenseClaimLine>(entity =>
        {
            entity.ToTable("expense_claim_lines");
            entity.HasKey(x => x.Id);
            entity.Property(x => x.Amount).HasPrecision(14, 2);
            entity.Property(x => x.CategoryCode).HasMaxLength(80);
            entity.Property(x => x.CategoryName).HasMaxLength(160);
            entity.Property(x => x.Description).HasMaxLength(500);
            entity.Property(x => x.ReceiptStorageKey).HasMaxLength(500);
            entity.Property(x => x.ReceiptFileName).HasMaxLength(255);
            entity.Property(x => x.ReceiptContentType).HasMaxLength(120);
            entity.HasIndex(x => new { x.TenantId, x.ClaimId, x.LineNumber });
            entity.HasIndex(x => new { x.TenantId, x.CategoryCode, x.ExpenseDate });
        });
    }
}
