using Zayra.Api.Domain.Entities;

namespace Zayra.Api.Models;

/// <summary>
/// One cell of a grade entitlement grid: what an employee of <see cref="GradeId"/> is entitled to under
/// one pay component code, from <see cref="EffectiveFrom"/> to <see cref="EffectiveTo"/> (inclusive).
///
/// <para><b>Capability.</b> Grade-based loan limits (slice L1): the Facility component <c>LOAN_&lt;type&gt;</c>
/// carries, per grade, whether the grade may borrow, a per-loan maximum and a total-outstanding maximum.
/// The same table is the home of later grade entitlements (housing, ticket, medical tier), which is why it
/// is keyed by a component code rather than by loan type.</para>
///
/// <para><b>Close-only.</b> A row's values are never updated. Publishing a new value closes the row in
/// effect (<c>EffectiveTo = newFrom − 1</c>) and inserts a new one, in one transaction, so a loan's
/// <see cref="EmployeeLoan.GradeEntitlementId"/> witness always points at the figures it was decided under.
/// Overlap is impossible at the database: <c>EXCLUDE USING gist</c> over
/// (tenant, company_key, grade, component, daterange) — see <see cref="GradeEntitlementSql"/>.</para>
///
/// <para><b>Scope.</b> <see cref="CompanyId"/> NULL is the tenant-wide cell; a company cell overrides it for
/// that company's employees. <see cref="CompanyKey"/> is a stored generated column
/// (<c>COALESCE(company_id, nil uuid)</c>) so the exclusion treats "tenant-wide" as one scope.</para>
/// </summary>
public class GradeEntitlement : ITenantOwned, ICompanyScoped
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid TenantId { get; set; }
    public Guid? CompanyId { get; set; }

    /// <summary>Generated by the database; never written by the application.</summary>
    public Guid CompanyKey { get; private set; }

    public Guid GradeId { get; set; }
    public string PayComponentCode { get; set; } = string.Empty;
    public string EntitlementClass { get; set; } = PayEntitlementClasses.Facility;
    public bool Eligible { get; set; }

    /// <summary>See <see cref="GradeEntitlementValueTypes"/>.</summary>
    public string ValueType { get; set; } = GradeEntitlementValueTypes.EligibilityOnly;

    /// <summary>Fixed amount (ValueType Amount). For a loan facility: the per-loan maximum.</summary>
    public decimal? Amount { get; set; }

    /// <summary>The multiple of monthly basic or gross salary (ValueType MultipleOf*), e.g. 3.0000.</summary>
    public decimal? Rate { get; set; }

    /// <summary>Facility only: the most this grade may owe on this component at once.</summary>
    public decimal? MaxOutstandingAmount { get; set; }

    public string? Note { get; set; }
    public string? SourceRule { get; set; }
    public DateOnly EffectiveFrom { get; set; }
    public DateOnly? EffectiveTo { get; set; }
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public Guid? CreatedBy { get; set; }

    public bool IsInEffect(DateOnly on) => EffectiveFrom <= on && (EffectiveTo is null || EffectiveTo.Value >= on);
}

/// <summary>Value set of <c>grade_entitlements.value_type</c> (CHECK ck_grade_entitlements__value_type).</summary>
public static class GradeEntitlementValueTypes
{
    public const string Amount = "Amount";
    public const string MultipleOfBasic = "MultipleOfBasic";
    public const string MultipleOfGross = "MultipleOfGross";
    public const string EligibilityOnly = "EligibilityOnly";
    public static readonly string[] All = [Amount, MultipleOfBasic, MultipleOfGross, EligibilityOnly];
}

/// <summary>
/// The DDL EF cannot model for <c>grade_entitlements</c>. One definition, executed by the migration that
/// creates the table and by the Postgres test fixture (which builds its schema with EnsureCreated), so the
/// constraint the tests prove is byte-for-byte the constraint production gets.
/// </summary>
public static class GradeEntitlementSql
{
    public const string ExclusionName = "ex_grade_entitlements__no_overlap";

    /// <summary>btree_gist lets a GiST exclusion compare uuid/text with "=" next to the daterange "&amp;&amp;".
    /// A trusted extension on PostgreSQL 13+, so the database owner can create it (Neon included).</summary>
    public const string CreateExtension = "CREATE EXTENSION IF NOT EXISTS btree_gist;";

    public const string AddExclusion =
        "ALTER TABLE grade_entitlements ADD CONSTRAINT " + ExclusionName + " EXCLUDE USING gist (" +
        "tenant_id WITH =, company_key WITH =, grade_id WITH =, pay_component_code WITH =, " +
        "daterange(effective_from, COALESCE(effective_to, 'infinity'::date), '[]') WITH &&);";

    public const string DropExclusion =
        "ALTER TABLE grade_entitlements DROP CONSTRAINT IF EXISTS " + ExclusionName + ";";
}
